import copy

from ..constants import magpie_voice_catalog

OPENAI_ADAPTER = "openai_compatible"
AUDIO_CPP_ADAPTER = "audio_cpp"
GENERIC_JSON_ADAPTER = "generic_json"
ELEVENLABS_NATIVE_ADAPTER = "elevenlabs_native"
AZURE_SPEECH_ADAPTER = "azure_speech"

# audio.cpp v0.7.1 ships these model families.  The server remains the source
# of truth when it advertises a live catalogue; these entries keep a fresh or
# offline first-class service useful before its catalogue has been refreshed.
AUDIO_CPP_MODEL_CATALOG = [
    {
        "id": "qwen3_tts_1_7b_base_q8_0",
        "family": "qwen3_tts",
        "voice_mode": "cloning",
        "recommended_chunk_characters": 300,
    },
    {
        "id": "qwen3_tts_1_7b_customvoice_q8_0",
        "family": "qwen3_tts",
        "voice_mode": "prebuilt",
        "recommended_chunk_characters": 300,
    },
    {
        "id": "fish_audio_s2_pro_q8_0",
        "family": "fish_audio_s2",
        "voice_mode": "cloning",
    },
    {
        "id": "voxcpm2_q8_0",
        "family": "voxcpm2",
        "voice_mode": "cloning",
    },
    {
        "id": "magpie_tts_q8_0",
        "family": "magpie_tts",
        "voice_mode": "prebuilt",
    },
    {
        "id": "chatterbox_q8_0",
        "family": "chatterbox",
        "voice_mode": "cloning",
    },
    {
        "id": "omnivoice_q8_0",
        "family": "omnivoice",
        "voice_mode": "cloning",
    },
    {
        "id": "pocket_tts_english_q8_0",
        "family": "pocket_tts",
        "voice_mode": "hybrid",
    },
    {
        "id": "fireredtts3_base_q8_0",
        "family": "fireredtts3",
        "voice_mode": "cloning",
        "experimental": True,
    },
]
AUDIO_CPP_MODEL_VOICE_MODES = {
    item["id"]: item["voice_mode"] for item in AUDIO_CPP_MODEL_CATALOG
}
AUDIO_CPP_PREBUILT_VOICES = [
    "Aiden",
    "Dylan",
    "Eric",
    "Ono_Anna",
    "Ryan",
    "Serena",
    "Sohee",
    "Uncle_Fu",
    "Vivian",
    *magpie_voice_catalog(),
    "alba",
]

AZURE_SPEECH_MODELS = ["MAI-Voice-2", "MAI-Voice-2-Flash"]
AZURE_SPEECH_DEFAULT_MODEL = "MAI-Voice-2"
AZURE_SPEECH_DEFAULT_VOICE = "en-US-Ethan:MAI-Voice-2"
AZURE_SPEECH_DEFAULT_FLASH_VOICE = "en-US-Ethan:MAI-Voice-2-Flash"
AZURE_SPEECH_OUTPUT_FORMAT = "audio-24khz-160kbitrate-mono-mp3"
AZURE_SPEECH_SOURCE_URL = (
    "https://learn.microsoft.com/azure/ai-services/speech-service/mai-voices"
)

_AZURE_EXPRESSIVE_STYLES = (
    "angry",
    "confused",
    "determined",
    "disgusted",
    "embarrassed",
    "excited",
    "fearful",
    "happy",
    "hopeful",
    "jealous",
    "joyful",
    "regretful",
    "relieved",
    "sad",
    "shouting",
    "softvoice",
    "surprised",
    "whispering",
)
_AZURE_ES_EXPRESSIVE_STYLES = (
    "adventurous",
    "caring",
    "empathy",
    "curious",
    "encouraging",
    "excited",
    "friendly",
    "cheerful",
    "nostalgic",
    "reflective",
    "sad",
    "disappointed",
    "serious",
)

# These rows mirror Microsoft's published MAI-Voice prebuilt tables.  Keep
# the full short names because Azure expects the model suffix in the voice ID.
_AZURE_MAI_VOICE_ROWS = (
    (
        "MAI-Voice-2",
        "de-DE-Klaus:MAI-Voice-2",
        "de-DE",
        "German (Germany)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "de-DE-Mia:MAI-Voice-2",
        "de-DE",
        "German (Germany)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "en-AU-Lisa:MAI-Voice-2",
        "en-AU",
        "English (Australia)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "en-US-Ethan:MAI-Voice-2",
        "en-US",
        "English (United States)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "en-US-Grant:MAI-Voice-2",
        "en-US",
        "English (United States)",
        "Male",
        (),
    ),
    (
        "MAI-Voice-2",
        "en-US-Harper:MAI-Voice-2",
        "en-US",
        "English (United States)",
        "Female",
        (
            "angry",
            "confused",
            "determined",
            "embarrassed",
            "excited",
            "happy",
            "hopeful",
            "joyful",
            "regretful",
            "relieved",
            "sad",
            "shouting",
            "softvoice",
            "whispering",
        ),
    ),
    (
        "MAI-Voice-2",
        "en-US-Iris:MAI-Voice-2",
        "en-US",
        "English (United States)",
        "Female",
        (),
    ),
    (
        "MAI-Voice-2",
        "en-US-Jasper:MAI-Voice-2",
        "en-US",
        "English (United States)",
        "Male",
        (),
    ),
    (
        "MAI-Voice-2",
        "en-US-Olivia:MAI-Voice-2",
        "en-US",
        "English (United States)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "es-ES-Marta:MAI-Voice-2",
        "es-ES",
        "Spanish (Spain)",
        "Female",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "es-MX-Alejo:MAI-Voice-2",
        "es-MX",
        "Spanish (Mexico)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "es-MX-Valeria:MAI-Voice-2",
        "es-MX",
        "Spanish (Mexico)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "fr-FR-Marc:MAI-Voice-2",
        "fr-FR",
        "French (France)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "fr-FR-Soleil:MAI-Voice-2",
        "fr-FR",
        "French (France)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "hi-IN-Arjun:MAI-Voice-2",
        "hi-IN",
        "Hindi (India)",
        "Male",
        (
            "angry",
            "confused",
            "disgusted",
            "embarrassed",
            "excited",
            "fearful",
            "happy",
            "hopeful",
            "jealous",
            "joyful",
            "regretful",
            "sad",
            "surprised",
        ),
    ),
    (
        "MAI-Voice-2",
        "hi-IN-Dhruv:MAI-Voice-2",
        "hi-IN",
        "Hindi (India)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "hi-IN-Kavya:MAI-Voice-2",
        "hi-IN",
        "Hindi (India)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "hi-IN-Priya:MAI-Voice-2",
        "hi-IN",
        "Hindi (India)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "hu-HU-Bence:MAI-Voice-2",
        "hu-HU",
        "Hungarian (Hungary)",
        "Male",
        (),
    ),
    (
        "MAI-Voice-2",
        "hu-HU-Levente:MAI-Voice-2",
        "hu-HU",
        "Hungarian (Hungary)",
        "Male",
        (),
    ),
    (
        "MAI-Voice-2",
        "hu-HU-Lilla:MAI-Voice-2",
        "hu-HU",
        "Hungarian (Hungary)",
        "Female",
        (),
    ),
    (
        "MAI-Voice-2",
        "hu-HU-Réka:MAI-Voice-2",
        "hu-HU",
        "Hungarian (Hungary)",
        "Female",
        (),
    ),
    (
        "MAI-Voice-2",
        "it-IT-Luca:MAI-Voice-2",
        "it-IT",
        "Italian (Italy)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "it-IT-Rosa:MAI-Voice-2",
        "it-IT",
        "Italian (Italy)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "ko-KR-Hana:MAI-Voice-2",
        "ko-KR",
        "Korean (Korea)",
        "Female",
        (
            "angry",
            "confused",
            "determined",
            "embarrassed",
            "excited",
            "happy",
            "hopeful",
            "joyful",
            "regretful",
            "relieved",
            "sad",
            "softvoice",
            "surprised",
        ),
    ),
    (
        "MAI-Voice-2",
        "ko-KR-Junho:MAI-Voice-2",
        "ko-KR",
        "Korean (Korea)",
        "Male",
        (
            "angry",
            "confused",
            "determined",
            "embarrassed",
            "excited",
            "happy",
            "hopeful",
            "joyful",
            "relieved",
            "sad",
            "softvoice",
        ),
    ),
    (
        "MAI-Voice-2",
        "nl-NL-Fleur:MAI-Voice-2",
        "nl-NL",
        "Dutch (Netherlands)",
        "Female",
        (),
    ),
    (
        "MAI-Voice-2",
        "nl-NL-Sander:MAI-Voice-2",
        "nl-NL",
        "Dutch (Netherlands)",
        "Male",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "pt-BR-Caio:MAI-Voice-2",
        "pt-BR",
        "Portuguese (Brazil)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "pt-BR-Luana:MAI-Voice-2",
        "pt-BR",
        "Portuguese (Brazil)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "pt-BR-Pedro:MAI-Voice-2",
        "pt-BR",
        "Portuguese (Brazil)",
        "Male",
        (
            "confused",
            "determined",
            "embarrassed",
            "excited",
            "happy",
            "hopeful",
            "joyful",
            "regretful",
            "relieved",
            "sad",
            "softvoice",
            "surprised",
        ),
    ),
    (
        "MAI-Voice-2",
        "pt-BR-Rafael:MAI-Voice-2",
        "pt-BR",
        "Portuguese (Brazil)",
        "Male",
        (
            "angry",
            "confused",
            "determined",
            "embarrassed",
            "excited",
            "happy",
            "hopeful",
            "joyful",
            "regretful",
            "relieved",
            "sad",
            "softvoice",
            "surprised",
        ),
    ),
    (
        "MAI-Voice-2",
        "pt-PT-Rui:MAI-Voice-2",
        "pt-PT",
        "Portuguese (Portugal)",
        "Male",
        (
            "angry",
            "confused",
            "determined",
            "embarrassed",
            "excited",
            "happy",
            "hopeful",
            "joyful",
            "regretful",
            "relieved",
            "sad",
            "softvoice",
            "surprised",
        ),
    ),
    (
        "MAI-Voice-2",
        "ro-RO-Andrei:MAI-Voice-2",
        "ro-RO",
        "Romanian (Romania)",
        "Male",
        (),
    ),
    (
        "MAI-Voice-2",
        "ro-RO-Elena:MAI-Voice-2",
        "ro-RO",
        "Romanian (Romania)",
        "Female",
        (),
    ),
    (
        "MAI-Voice-2",
        "ro-RO-Ioana:MAI-Voice-2",
        "ro-RO",
        "Romanian (Romania)",
        "Female",
        (),
    ),
    (
        "MAI-Voice-2",
        "ro-RO-Radu:MAI-Voice-2",
        "ro-RO",
        "Romanian (Romania)",
        "Male",
        (),
    ),
    (
        "MAI-Voice-2",
        "ru-RU-Lev:MAI-Voice-2",
        "ru-RU",
        "Russian (Russia)",
        "Male",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "ru-RU-Masha:MAI-Voice-2",
        "ru-RU",
        "Russian (Russia)",
        "Female",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "th-TH-Krit:MAI-Voice-2",
        "th-TH",
        "Thai (Thailand)",
        "Male",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "th-TH-Nattapong:MAI-Voice-2",
        "th-TH",
        "Thai (Thailand)",
        "Male",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "tr-TR-Aydin:MAI-Voice-2",
        "tr-TR",
        "Turkish (Turkey)",
        "Male",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "tr-TR-Elif:MAI-Voice-2",
        "tr-TR",
        "Turkish (Turkey)",
        "Female",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "zh-CN-Bo:MAI-Voice-2",
        "zh-CN",
        "Chinese (Mandarin, Simplified)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2",
        "zh-CN-Lan:MAI-Voice-2",
        "zh-CN",
        "Chinese (Mandarin, Simplified)",
        "Female",
        (
            "angry",
            "confused",
            "disgusted",
            "embarrassed",
            "excited",
            "fearful",
            "happy",
            "joyful",
            "sad",
            "surprised",
        ),
    ),
    (
        "MAI-Voice-2",
        "zh-CN-Mei:MAI-Voice-2",
        "zh-CN",
        "Chinese (Mandarin, Simplified)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "de-DE-Klaus:MAI-Voice-2-Flash",
        "de-DE",
        "German (Germany)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "de-DE-Mia:MAI-Voice-2-Flash",
        "de-DE",
        "German (Germany)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "en-AU-Isla:MAI-Voice-2-Flash",
        "en-AU",
        "English (Australia)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "en-US-Ethan:MAI-Voice-2-Flash",
        "en-US",
        "English (United States)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "en-US-Harper:MAI-Voice-2-Flash",
        "en-US",
        "English (United States)",
        "Female",
        (
            "angry",
            "confused",
            "determined",
            "embarrassed",
            "excited",
            "happy",
            "hopeful",
            "joyful",
            "regretful",
            "relieved",
            "sad",
            "shouting",
            "softvoice",
            "whispering",
        ),
    ),
    (
        "MAI-Voice-2-Flash",
        "en-US-Olivia:MAI-Voice-2-Flash",
        "en-US",
        "English (United States)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "es-ES-Marta:MAI-Voice-2-Flash",
        "es-ES",
        "Spanish (Spain)",
        "Female",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "es-MX-Alejo:MAI-Voice-2-Flash",
        "es-MX",
        "Spanish (Mexico)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "es-MX-Valeria:MAI-Voice-2-Flash",
        "es-MX",
        "Spanish (Mexico)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "fr-FR-Marc:MAI-Voice-2-Flash",
        "fr-FR",
        "French (France)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "fr-FR-Soleil:MAI-Voice-2-Flash",
        "fr-FR",
        "French (France)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "hi-IN-Arjun:MAI-Voice-2-Flash",
        "hi-IN",
        "Hindi (India)",
        "Male",
        (
            "angry",
            "confused",
            "disgusted",
            "embarrassed",
            "excited",
            "fearful",
            "happy",
            "hopeful",
            "jealous",
            "joyful",
            "regretful",
            "sad",
            "surprised",
        ),
    ),
    (
        "MAI-Voice-2-Flash",
        "hi-IN-Dhruv:MAI-Voice-2-Flash",
        "hi-IN",
        "Hindi (India)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "hi-IN-Kavya:MAI-Voice-2-Flash",
        "hi-IN",
        "Hindi (India)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "hi-IN-Priya:MAI-Voice-2-Flash",
        "hi-IN",
        "Hindi (India)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "hu-HU-Bence:MAI-Voice-2-Flash",
        "hu-HU",
        "Hungarian (Hungary)",
        "Male",
        (),
    ),
    (
        "MAI-Voice-2-Flash",
        "hu-HU-Levente:MAI-Voice-2-Flash",
        "hu-HU",
        "Hungarian (Hungary)",
        "Male",
        (),
    ),
    (
        "MAI-Voice-2-Flash",
        "hu-HU-Lilla:MAI-Voice-2-Flash",
        "hu-HU",
        "Hungarian (Hungary)",
        "Female",
        (),
    ),
    (
        "MAI-Voice-2-Flash",
        "hu-HU-Réka:MAI-Voice-2-Flash",
        "hu-HU",
        "Hungarian (Hungary)",
        "Female",
        (),
    ),
    (
        "MAI-Voice-2-Flash",
        "it-IT-Luca:MAI-Voice-2-Flash",
        "it-IT",
        "Italian (Italy)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "it-IT-Rosa:MAI-Voice-2-Flash",
        "it-IT",
        "Italian (Italy)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "ko-KR-Haena:MAI-Voice-2-Flash",
        "ko-KR",
        "Korean (Korea)",
        "Female",
        (
            "angry",
            "confused",
            "determined",
            "embarrassed",
            "excited",
            "happy",
            "hopeful",
            "joyful",
            "regretful",
            "relieved",
            "sad",
            "softvoice",
            "surprised",
        ),
    ),
    (
        "MAI-Voice-2-Flash",
        "ko-KR-Junho:MAI-Voice-2-Flash",
        "ko-KR",
        "Korean (Korea)",
        "Male",
        (
            "angry",
            "confused",
            "determined",
            "embarrassed",
            "excited",
            "happy",
            "hopeful",
            "joyful",
            "relieved",
            "sad",
            "softvoice",
        ),
    ),
    (
        "MAI-Voice-2-Flash",
        "nl-NL-Sander:MAI-Voice-2-Flash",
        "nl-NL",
        "Dutch (Netherlands)",
        "Male",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "pt-BR-Caio:MAI-Voice-2-Flash",
        "pt-BR",
        "Portuguese (Brazil)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "pt-BR-Luana:MAI-Voice-2-Flash",
        "pt-BR",
        "Portuguese (Brazil)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "pt-BR-Pedro:MAI-Voice-2-Flash",
        "pt-BR",
        "Portuguese (Brazil)",
        "Male",
        (
            "confused",
            "determined",
            "embarrassed",
            "excited",
            "happy",
            "hopeful",
            "joyful",
            "regretful",
            "relieved",
            "sad",
            "softvoice",
            "surprised",
        ),
    ),
    (
        "MAI-Voice-2-Flash",
        "pt-BR-Rafael:MAI-Voice-2-Flash",
        "pt-BR",
        "Portuguese (Brazil)",
        "Male",
        (
            "angry",
            "confused",
            "determined",
            "embarrassed",
            "excited",
            "happy",
            "hopeful",
            "joyful",
            "regretful",
            "relieved",
            "sad",
            "softvoice",
            "surprised",
        ),
    ),
    (
        "MAI-Voice-2-Flash",
        "pt-PT-Rui:MAI-Voice-2-Flash",
        "pt-PT",
        "Portuguese (Portugal)",
        "Male",
        (
            "angry",
            "confused",
            "determined",
            "embarrassed",
            "excited",
            "happy",
            "hopeful",
            "joyful",
            "regretful",
            "relieved",
            "sad",
            "softvoice",
            "surprised",
        ),
    ),
    (
        "MAI-Voice-2-Flash",
        "ro-RO-Andrei:MAI-Voice-2-Flash",
        "ro-RO",
        "Romanian (Romania)",
        "Male",
        (),
    ),
    (
        "MAI-Voice-2-Flash",
        "ro-RO-Elena:MAI-Voice-2-Flash",
        "ro-RO",
        "Romanian (Romania)",
        "Female",
        (),
    ),
    (
        "MAI-Voice-2-Flash",
        "ro-RO-Ioana:MAI-Voice-2-Flash",
        "ro-RO",
        "Romanian (Romania)",
        "Female",
        (),
    ),
    (
        "MAI-Voice-2-Flash",
        "ro-RO-Radu:MAI-Voice-2-Flash",
        "ro-RO",
        "Romanian (Romania)",
        "Male",
        (),
    ),
    (
        "MAI-Voice-2-Flash",
        "ru-RU-Lev:MAI-Voice-2-Flash",
        "ru-RU",
        "Russian (Russia)",
        "Male",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "ru-RU-Masha:MAI-Voice-2-Flash",
        "ru-RU",
        "Russian (Russia)",
        "Female",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "th-TH-Krit:MAI-Voice-2-Flash",
        "th-TH",
        "Thai (Thailand)",
        "Male",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "th-TH-Nattapong:MAI-Voice-2-Flash",
        "th-TH",
        "Thai (Thailand)",
        "Male",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "tr-TR-Aydın:MAI-Voice-2-Flash",
        "tr-TR",
        "Turkish (Türkiye)",
        "Male",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "tr-TR-Elif:MAI-Voice-2-Flash",
        "tr-TR",
        "Turkish (Türkiye)",
        "Female",
        _AZURE_ES_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "zh-CN-Bo:MAI-Voice-2-Flash",
        "zh-CN",
        "Chinese (Mandarin, Simplified)",
        "Male",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "zh-CN-Lan:MAI-Voice-2-Flash",
        "zh-CN",
        "Chinese (Mandarin, Simplified)",
        "Female",
        (
            "angry",
            "confused",
            "disgusted",
            "embarrassed",
            "excited",
            "fearful",
            "happy",
            "joyful",
            "sad",
            "surprised",
        ),
    ),
    (
        "MAI-Voice-2-Flash",
        "zh-CN-Mei:MAI-Voice-2-Flash",
        "zh-CN",
        "Chinese (Mandarin, Simplified)",
        "Female",
        _AZURE_EXPRESSIVE_STYLES,
    ),
    (
        "MAI-Voice-2-Flash",
        "zh-CN-Wei:MAI-Voice-2-Flash",
        "zh-CN",
        "Chinese (Mandarin, Simplified)",
        "Male",
        (
            "angry",
            "confused",
            "disgusted",
            "embarrassed",
            "excited",
            "fearful",
            "happy",
            "hopeful",
            "jealous",
            "joyful",
            "regretful",
            "sad",
            "surprised",
        ),
    ),
)

AZURE_SPEECH_VOICE_CATALOGUES = {
    model: [row[1] for row in _AZURE_MAI_VOICE_ROWS if row[0] == model]
    for model in AZURE_SPEECH_MODELS
}
AZURE_SPEECH_VOICES = [row[1] for row in _AZURE_MAI_VOICE_ROWS]
AZURE_SPEECH_VOICE_METADATA = {
    f"{model}:{voice}": {
        "id": voice,
        "voice_id": voice,
        "model": model,
        "locale": locale,
        "language": language,
        "gender": gender,
        "styles": list(styles),
        "source": AZURE_SPEECH_SOURCE_URL,
    }
    for model, voice, locale, language, gender, styles in _AZURE_MAI_VOICE_ROWS
}


def _openai_profile(
    profile_id: str,
    name: str,
    api_base: str,
    source_url: str,
    models: list[str],
    voices: list[str] | None = None,
    voices_path: str = "",
    notes: str = "",
    auth_mode: str = "bearer",
    direct_http: bool = False,
    speech_path: str = "/v1/audio/speech",
    supports_prebuilt_voices: bool = True,
    models_are_manual: bool = False,
    credential_required: bool = False,
) -> dict:
    return {
        "id": profile_id,
        "name": name,
        "description": "OpenAI-compatible JSON speech API.",
        "source_url": source_url,
        "api_base": api_base,
        "provider": "openai",
        "adapter": OPENAI_ADAPTER,
        "speech_path": speech_path,
        "models_path": "/v1/models",
        "voices_path": voices_path,
        "request_fields": {
            "text": "input",
            "model": "model",
            "voice": "voice",
            "speed": "speed",
            "format": "response_format",
        },
        "request_defaults": {},
        "models": models,
        "voices": voices or [],
        "supports_prebuilt_voices": supports_prebuilt_voices,
        "auth_mode": auth_mode,
        "direct_http": direct_http,
        "models_are_manual": models_are_manual,
        "credential_required": credential_required,
        "notes": notes,
    }


def _audio_cpp_profile() -> dict:
    """Return the opt-in profile for an externally managed audio.cpp server."""

    model_catalog = copy.deepcopy(AUDIO_CPP_MODEL_CATALOG)
    model_ids = [str(item["id"]) for item in model_catalog]
    prebuilt_voices = list(dict.fromkeys(AUDIO_CPP_PREBUILT_VOICES))

    return {
        "id": "audio-cpp-experimental",
        "profile_id": "audio-cpp-experimental",
        "name": "External audio.cpp endpoint",
        "description": (
            "Externally managed audio.cpp server with live model and model-specific "
            "voice discovery. The legacy profile ID remains compatible."
        ),
        "source_url": "https://github.com/0xShug0/audio.cpp",
        "api_base": "http://127.0.0.1:8080",
        "provider": "openai",
        "adapter": AUDIO_CPP_ADAPTER,
        "speech_path": "/v1/audio/speech",
        "models_path": "/v1/models",
        "voices_path": "/v1/audio/voices",
        "request_fields": {
            "text": "input",
            "model": "model",
            "voice": "voice",
            "speed": "",
            "format": "response_format",
        },
        "request_defaults": {},
        "models": model_ids,
        "model_catalog": model_catalog,
        "model_voice_modes": copy.deepcopy(AUDIO_CPP_MODEL_VOICE_MODES),
        # audio.cpp voice names are model-specific. Keep the provider-wide
        # fallback empty so Qwen, Magpie, and Pocket presets never leak into
        # cloning-only models when the live catalogue is unavailable.
        "voices": [],
        "voice_catalogues": {
            "qwen3_tts_1_7b_customvoice_q8_0": prebuilt_voices[:9],
            "magpie_tts_q8_0": list(magpie_voice_catalog()),
            "pocket_tts_english_q8_0": ["alba"],
        },
        "supports_prebuilt_voices": True,
        "supports_voice_cloning": True,
        "supports_voice_deletion": False,
        "voice_reference_text": "optional",
        "auth_mode": "none",
        "direct_http": True,
        "models_are_manual": False,
        "credential_required": False,
        "notes": (
            "Start audiocpp_server with its JSON config, then refresh the TTS "
            "catalogue. Configure audio.cpp voice presets or voice_dir (including "
            "prompt_text where a model needs a reference transcript). Pandrator "
            "links Voice Library references locally; it does not upload or delete "
            "server voices."
        ),
    }


def _generic_profile(
    profile_id: str,
    name: str,
    api_base: str,
    source_url: str,
    speech_path: str,
    request_fields: dict[str, str],
    request_defaults: dict | None = None,
    models: list[str] | None = None,
    voices: list[str] | None = None,
    supports_prebuilt_voices: bool = False,
    notes: str = "",
    credential_required: bool = False,
) -> dict:
    return {
        "id": profile_id,
        "name": name,
        "description": "Known JSON speech API mapping.",
        "source_url": source_url,
        "api_base": api_base,
        "provider": "openai",
        "adapter": GENERIC_JSON_ADAPTER,
        "speech_path": speech_path,
        "models_path": "",
        "voices_path": "",
        "request_fields": {
            key: str(request_fields.get(key) or "")
            for key in ("text", "model", "voice", "speed", "format")
        },
        "request_defaults": request_defaults or {},
        "models": models or [],
        "voices": voices or [],
        "supports_prebuilt_voices": supports_prebuilt_voices,
        "credential_required": credential_required,
        "notes": notes,
    }


def _elevenlabs_profile() -> dict:
    return {
        "id": "elevenlabs",
        "profile_id": "elevenlabs-native",
        "name": "ElevenLabs (native API)",
        "description": (
            "Native ElevenLabs text-to-speech API. This is not an OpenAI-compatible endpoint; "
            "it requires an ElevenLabs API key."
        ),
        "source_url": "https://elevenlabs.io/docs/api-reference/text-to-speech",
        "api_base": "https://api.elevenlabs.io",
        "provider": "elevenlabs",
        "adapter": ELEVENLABS_NATIVE_ADAPTER,
        "speech_path": "/v1/text-to-speech/{voice_id}",
        "models_path": "/v1/models",
        "voices_path": "/v2/voices",
        "request_fields": {
            "text": "text",
            "model": "model_id",
            "voice": "voice_id",
            "speed": "",
            "format": "",
        },
        "request_defaults": {"output_format": "mp3_44100_128"},
        "models": ["eleven_multilingual_v2"],
        "voices": [],
        "supports_prebuilt_voices": True,
        "auth_mode": "xi-api-key",
        "direct_http": True,
        "credential_required": True,
        "notes": (
            "The voice ID is URL-encoded in /v1/text-to-speech/{voice_id}; models and voices "
            "are discovered from ElevenLabs' official catalogue endpoints."
        ),
    }


def _azure_speech_profile() -> dict:
    model_catalog = [
        {
            "id": model,
            "name": model.replace("MAI-Voice-2-Flash", "MAI Voice 2 Flash").replace(
                "MAI-Voice-2", "MAI Voice 2"
            ),
            "unit": "characters",
            "source": "Azure pricing",
            "source_url": AZURE_SPEECH_SOURCE_URL,
        }
        for model in AZURE_SPEECH_MODELS
    ]
    return {
        "id": "azure-speech-mai-voice-2",
        "profile_id": "azure-speech-mai-voice-2",
        "name": "Azure Speech · MAI Voice 2",
        "description": (
            "Native Azure Speech SSML endpoint for the prebuilt MAI Voice 2 models."
        ),
        "source_url": AZURE_SPEECH_SOURCE_URL,
        "api_base": "https://YOUR-REGION.tts.speech.microsoft.com",
        "provider": "azure",
        "adapter": AZURE_SPEECH_ADAPTER,
        "speech_path": "/cognitiveservices/v1",
        "models_path": "",
        "voices_path": "",
        "request_fields": {
            "text": "ssml",
            "model": "",
            "voice": "",
            "speed": "",
            "format": "",
        },
        "request_defaults": {"output_format": AZURE_SPEECH_OUTPUT_FORMAT},
        "settings": {
            "azure_speech_style": "",
            "azure_speech_style_degree": 1.0,
            "azure_speech_output_format": AZURE_SPEECH_OUTPUT_FORMAT,
        },
        "models": list(AZURE_SPEECH_MODELS),
        "default_model": AZURE_SPEECH_DEFAULT_MODEL,
        "voices": list(AZURE_SPEECH_VOICES),
        "default_voice": AZURE_SPEECH_DEFAULT_VOICE,
        "voice_catalogues": {
            model: list(voices)
            for model, voices in AZURE_SPEECH_VOICE_CATALOGUES.items()
        },
        "default_voices": {
            AZURE_SPEECH_MODELS[0]: AZURE_SPEECH_DEFAULT_VOICE,
            AZURE_SPEECH_MODELS[1]: AZURE_SPEECH_DEFAULT_FLASH_VOICE,
        },
        "voice_metadata": copy.deepcopy(AZURE_SPEECH_VOICE_METADATA),
        "model_catalog": model_catalog,
        "generation_prompt_models": [],
        "pricing": {
            model: {"unit": "characters", "source": "Azure pricing"}
            for model in AZURE_SPEECH_MODELS
        },
        "supports_prebuilt_voices": True,
        "auth_mode": "subscription-key",
        "direct_http": True,
        "credential_required": True,
        "api_key_env": "AZURE_SPEECH_KEY",
        "notes": (
            "Static prebuilt voice catalogue copied from Microsoft's MAI-Voice docs. "
            "This profile intentionally excludes gated instant voice cloning."
        ),
    }


_VOXTRAL_RUST_VOICES = [
    "casual_female",
    "casual_male",
    "cheerful_female",
    "neutral_female",
    "neutral_male",
    "fr_male",
    "fr_female",
    "es_male",
    "es_female",
    "de_male",
    "de_female",
    "pt_male",
    "pt_female",
    "it_male",
    "it_female",
    "nl_male",
    "nl_female",
    "ar_male",
    "hi_male",
    "hi_female",
]


TTS_PROVIDER_PROFILES = [
    _audio_cpp_profile(),
    _elevenlabs_profile(),
    _azure_speech_profile(),
    _openai_profile(
        "azure-openai-v1",
        "Azure OpenAI (v1 TTS)",
        "https://YOUR-RESOURCE.openai.azure.com",
        "https://learn.microsoft.com/azure/foundry/openai/reference-preview-latest?view=foundry-classic",
        [],
        [],
        notes="Enter your Azure resource URL and add each deployed TTS model/deployment name manually.",
        auth_mode="api-key",
        direct_http=True,
        speech_path="/openai/v1/audio/speech?api-version=preview",
        supports_prebuilt_voices=False,
        models_are_manual=True,
        credential_required=True,
    ),
    _openai_profile(
        "pandrator-xtts2-api",
        "XTTS v2 - lukaszliniewicz/xtts2_api",
        "http://127.0.0.1:8020",
        "https://github.com/lukaszliniewicz/xtts2_api",
        ["tts_models/multilingual/multi-dataset/xtts_v2"],
        voices_path="/v1/files",
        notes="Alternate custom connection to Pandrator's installer-supported XTTS2 API. Discover Models/Voices lists uploaded voice file IDs.",
    ),
    _openai_profile(
        "pandrator-voxcpm-fastapi",
        "VoxCPM2 - lukaszliniewicz/voxcpm_fastapi",
        "http://127.0.0.1:8020",
        "https://github.com/lukaszliniewicz/voxcpm_fastapi",
        ["openbmb/VoxCPM2", "voxcpm2"],
        ["default"],
        notes="Alternate custom connection to Pandrator's installer-supported VoxCPM2 server.",
    ),
    _openai_profile(
        "pandrator-fishs2-fastapi",
        "FishS2 - lukaszliniewicz/fishs2-cpp-fastapi",
        "http://127.0.0.1:8020",
        "https://github.com/lukaszliniewicz/fishs2-cpp-fastapi",
        ["fishaudio/s2-pro", "fishs2", "fish-s2", "s2-pro"],
        ["default"],
        notes="Alternate custom connection to Pandrator's installer-supported FishS2 server.",
    ),
    _openai_profile(
        "pandrator-voxtral-fastapi",
        "Voxtral - lukaszliniewicz/voxtral-fastapi",
        "http://127.0.0.1:8000",
        "https://github.com/lukaszliniewicz/voxtral-fastapi",
        ["auto", "gguf", "bf16"],
        ["casual_female"],
        voices_path="/v1/audio/voices",
        notes="Alternate custom connection to Pandrator's installer-supported Voxtral server.",
    ),
    _openai_profile(
        "pandrator-chatterbox-fastapi",
        "Chatterbox - lukaszliniewicz/chatterbox-fastapi",
        "http://127.0.0.1:8040",
        "https://github.com/lukaszliniewicz/chatterbox-fastapi",
        ["chatterbox-turbo", "chatterbox-multilingual", "chatterbox-en"],
        voices_path="/v1/files",
        notes="Alternate custom connection to Pandrator's installer-supported Chatterbox server.",
    ),
    _openai_profile(
        "pandrator-kobold-qwen-fastapi",
        "Qwen3-TTS - lukaszliniewicz/kobold-qwen-fastapi",
        "http://127.0.0.1:8042",
        "https://github.com/lukaszliniewicz/kobold-qwen-fastapi",
        ["qwen3-tts"],
        ["kobo"],
        voices_path="/v1/audio/voices",
        notes="Alternate custom connection to Pandrator's installer-supported Qwen3-TTS KoboldCpp wrapper.",
    ),
    _openai_profile(
        "chatterbox-travisvn",
        "Chatterbox - travisvn/chatterbox-tts-api",
        "http://127.0.0.1:4123",
        "https://github.com/travisvn/chatterbox-tts-api",
        ["chatterbox-tts-1"],
        ["alloy"],
        voices_path="/voices",
        notes="Default port is 4123. The wrapper also offers multipart voice-library management outside this profile.",
    ),
    _openai_profile(
        "chatterbox-brioch",
        "Chatterbox - Brioch/chatterbox-tts-api",
        "http://127.0.0.1:5001",
        "https://github.com/Brioch/chatterbox-tts-api",
        ["Chatterbox", "Chatterbox-Multilingual", "Chatterbox-Turbo"],
        notes="Voice names correspond to reference files mounted into the wrapper's voices directory.",
    ),
    _openai_profile(
        "voxtral-second-state",
        "Voxtral - second-state/voxtral_tts_rs",
        "http://127.0.0.1:8080",
        "https://github.com/second-state/voxtral_tts_rs",
        ["voxtral-4b-tts"],
        _VOXTRAL_RUST_VOICES,
        notes="Uses non-streaming requests because Pandrator expects a complete audio response.",
    ),
    _openai_profile(
        "voxtral-vllm-omni",
        "Voxtral - vLLM-Omni server",
        "http://127.0.0.1:8091",
        "https://github.com/vllm-project/vllm-omni",
        ["mistralai/Voxtral-4B-TTS-2603"],
        ["casual_female", "casual_male"],
        notes="The official Voxtral launch example uses port 8091; adjust it to match your launch command.",
    ),
    _openai_profile(
        "cosyvoice-jianchang512",
        "CosyVoice - jianchang512/cosyvoice-api",
        "http://127.0.0.1:9233",
        "https://github.com/jianchang512/cosyvoice-api",
        ["tts-1"],
        [
            "\u4e2d\u6587\u5973",
            "\u4e2d\u6587\u7537",
            "\u65e5\u8bed\u7537",
            "\u7ca4\u8bed\u5973",
            "\u82f1\u6587\u5973",
            "\u82f1\u6587\u7537",
            "\u97e9\u8bed\u5973",
        ],
        notes="The wrapper's current OpenAI-compatible endpoint defaults to port 9233.",
    ),
    _generic_profile(
        "matcha-projecte-aina",
        "Matcha-TTS - projecte-aina/tts-api",
        "http://127.0.0.1:8000",
        "https://github.com/projecte-aina/tts-api",
        "/api/tts",
        {"text": "text", "voice": "voice"},
        {"type": "text", "language": "ca-es"},
        models=["matcha-tts"],
        voices=["quim", "ona", "lluc"],
        supports_prebuilt_voices=True,
        notes="The default language is ca-es; change the server/profile mapping if another deployed model requires it.",
    ),
    _generic_profile(
        "styletts2-salad",
        "StyleTTS2 - SaladTechnologies/styletts2-api",
        "http://127.0.0.1:4321",
        "https://github.com/SaladTechnologies/styletts2-api",
        "/generate",
        {"text": "text"},
        models=["styletts2"],
        notes="The upstream REST contract documents a text-only POST /generate request.",
    ),
    _generic_profile(
        "fish-speech-official",
        "Fish Speech - fishaudio/fish-speech API server",
        "http://127.0.0.1:8080",
        "https://github.com/fishaudio/fish-speech",
        "/v1/tts",
        {"text": "text", "voice": "reference_id", "format": "format"},
        {"normalize": True, "latency": "normal"},
        models=["fish-speech"],
        supports_prebuilt_voices=True,
        notes="The voice value is sent as reference_id. Inline reference audio/text payloads are not configured by this profile.",
    ),
    _openai_profile(
        "open-unified-tts",
        "Open Unified TTS - loserbcc/open-unified-tts",
        "http://127.0.0.1:8765",
        "https://github.com/loserbcc/open-unified-tts",
        ["tts-1"],
        ["bf_emma", "am_adam"],
        voices_path="/v1/voices",
        notes="The active backend and available voices are configured inside Open Unified TTS.",
    ),
    _openai_profile(
        "qwen3-second-state",
        "Qwen3-TTS - second-state/qwen3_audio_api",
        "http://127.0.0.1:8000",
        "https://github.com/second-state/qwen3_audio_api",
        ["qwen3-tts"],
        ["Vivian", "Ryan", "Serena"],
        notes="This profile covers preset voices. Reference-audio cloning fields require additional configuration.",
    ),
    _openai_profile(
        "kokoro-remsky",
        "Kokoro - remsky/Kokoro-FastAPI",
        "http://127.0.0.1:8880",
        "https://github.com/remsky/Kokoro-FastAPI",
        ["kokoro"],
        ["af_heart", "af_bella", "af_sky", "am_adam", "bf_emma"],
        voices_path="/v1/audio/voices",
        notes="This is an alternate custom connection to Kokoro-FastAPI, separate from Pandrator's first-class Kokoro service.",
    ),
    _generic_profile(
        "piper-native-http",
        "Piper - native piper.http_server",
        "http://127.0.0.1:5000",
        "https://github.com/OHF-Voice/piper1-gpl",
        "/",
        {"text": "text"},
        models=["piper"],
        notes="The native server uses its configured model and accepts JSON containing text at POST /.",
    ),
    _openai_profile(
        "piper-kamil-krawiec",
        "Piper - Kamil-Krawiec/piper-tts-http-server",
        "http://127.0.0.1:5000",
        "https://github.com/Kamil-Krawiec/piper-tts-http-server",
        ["piper"],
        notes="Voice names use Piper identifiers such as en_US-lessac-medium and are downloaded on demand.",
    ),
]


def list_tts_provider_profiles() -> list[dict]:
    return copy.deepcopy(TTS_PROVIDER_PROFILES)


def get_tts_provider_profile(profile_id: str) -> dict | None:
    normalized_id = str(profile_id or "").strip()
    for profile in TTS_PROVIDER_PROFILES:
        if profile["id"] == normalized_id:
            return copy.deepcopy(profile)
    return None
