"""Pure MCP handler functions, separated from protocol registration."""

from .dispatch import (
    claim_dispatch_batch,
    create_dispatch_run,
    get_dispatch_run,
    list_dispatch_runs,
    release_dispatch_batch,
    renew_dispatch_batch,
    submit_dispatch_batch,
)
from .e2e import (
    browse_local_sources,
    configure_tts,
    download_artifact,
    import_local_source,
    list_generation_runs,
    plan_export_variant,
    tts_catalog,
)
from .generation import (
    assemble_generation_run,
    list_generation_segments,
    regenerate_segments,
    select_take,
    update_generation_segment,
)
from .guidance import explain_system
from .inventory import list_artifacts, provider_status, voice_catalog
from .manager import (
    control_runtime,
    execute_component_plan,
    manager_doctor,
    manager_status,
    plan_component_change,
)
from .recommendations import recommend_next_steps
from .sessions import (
    attach_existing_source,
    create_session,
    get_session,
    get_session_settings,
    get_workflow,
    import_subtitles,
    list_sessions,
    list_sources,
    patch_subtitle_cues,
    preview_subtitles,
    replace_subtitle_text,
    update_session,
    update_session_settings,
)
from .source_cleaning_dispatch import (
    claim_source_cleaning_dispatch_batch,
    create_source_cleaning_dispatch_run,
    get_source_cleaning_dispatch_run,
    inspect_source_cleaning_dispatch_extraction,
    list_source_cleaning_dispatch_runs,
    release_source_cleaning_dispatch_batch,
    renew_source_cleaning_dispatch_batch,
    submit_source_cleaning_dispatch_batch,
)
from .speech_optimization_dispatch import (
    claim_speech_optimization_dispatch_batch,
    create_speech_optimization_dispatch_run,
    get_speech_optimization_dispatch_run,
    list_speech_optimization_dispatch_runs,
    release_speech_optimization_dispatch_batch,
    renew_speech_optimization_dispatch_batch,
    submit_speech_optimization_dispatch_batch,
)
from .system import capabilities, system_status, target_status
from .work import cancel_work, get_work, get_work_log, list_work
from .workflow import execute_workflow_plan, plan_workflow

__all__ = [
    "assemble_generation_run",
    "attach_existing_source",
    "browse_local_sources",
    "capabilities",
    "claim_dispatch_batch",
    "claim_source_cleaning_dispatch_batch",
    "claim_speech_optimization_dispatch_batch",
    "cancel_work",
    "control_runtime",
    "configure_tts",
    "create_session",
    "create_dispatch_run",
    "create_source_cleaning_dispatch_run",
    "create_speech_optimization_dispatch_run",
    "explain_system",
    "download_artifact",
    "execute_workflow_plan",
    "execute_component_plan",
    "get_session",
    "get_dispatch_run",
    "get_source_cleaning_dispatch_run",
    "get_speech_optimization_dispatch_run",
    "inspect_source_cleaning_dispatch_extraction",
    "import_local_source",
    "import_subtitles",
    "get_session_settings",
    "get_work",
    "get_work_log",
    "get_workflow",
    "list_artifacts",
    "list_generation_runs",
    "list_generation_segments",
    "list_dispatch_runs",
    "list_source_cleaning_dispatch_runs",
    "list_speech_optimization_dispatch_runs",
    "list_sessions",
    "list_sources",
    "list_work",
    "manager_doctor",
    "manager_status",
    "patch_subtitle_cues",
    "plan_workflow",
    "plan_export_variant",
    "plan_component_change",
    "preview_subtitles",
    "provider_status",
    "recommend_next_steps",
    "regenerate_segments",
    "release_dispatch_batch",
    "release_source_cleaning_dispatch_batch",
    "release_speech_optimization_dispatch_batch",
    "renew_dispatch_batch",
    "renew_source_cleaning_dispatch_batch",
    "renew_speech_optimization_dispatch_batch",
    "replace_subtitle_text",
    "select_take",
    "system_status",
    "submit_dispatch_batch",
    "submit_source_cleaning_dispatch_batch",
    "submit_speech_optimization_dispatch_batch",
    "target_status",
    "tts_catalog",
    "update_generation_segment",
    "update_session",
    "update_session_settings",
    "voice_catalog",
]
