<script lang="ts">
  import { page } from '$app/state';import { Check, Play, Square } from '@lucide/svelte';import { api } from '$lib/api';import SettingsPanel from '$lib/SettingsPanel.svelte';
  const sessionId=String(page.params.id);let sources=$state<any[]>([]);let runs=$state<any[]>([]);let selectedSource=$state('');let selectedRun=$state<any>(null);let steps=$state<any[]>([]);let error=$state('');
  async function load(){sources=(await api<{items:any[]}>(`/sessions/${sessionId}/sources`)).items.filter((item:any)=>item.artifact_id);selectedSource ||= sources.find((item:any)=>item.attachment.is_current)?.artifact_id??sources[0]?.artifact_id??'';runs=(await api<{items:any[]}>(`/sessions/${sessionId}/agent-runs`)).items;if(runs[0])await selectRun(runs[0])}load();
  async function selectRun(run:any){selectedRun=run;steps=(await api<{items:any[]}>(`/agent-runs/${run.id}/steps`)).items}
  async function run(){try{const settings=await api<any>(`/sessions/${sessionId}/settings/source_cleaning`);const created=await api<any>(`/sessions/${sessionId}/agent-runs`,{method:'POST',body:JSON.stringify({source_artifact_id:selectedSource,settings:settings.effective})});selectedRun=created;steps=[];await load()}catch(caught){error=caught instanceof Error?caught.message:String(caught)}}
  async function cancel(){if(selectedRun?.job_id)await api(`/jobs/${selectedRun.job_id}/cancel`,{method:'POST'})}
  async function accept(){if(selectedRun){selectedRun=await api(`/agent-runs/${selectedRun.id}/accept`,{method:'POST'});await load()}}
</script>
<div class="space-y-5"><div class="flex flex-wrap items-end justify-between gap-4"><div><h2 class="text-2xl font-semibold">Source cleaning</h2><p class="muted mt-2">Inspect deterministic extraction and the agentic phase loop without exposing private model reasoning.</p></div><div class="flex gap-2"><select bind:value={selectedSource} class="rounded-xl border border-[var(--line)] bg-[var(--paper)] px-3 py-2 text-sm">{#each sources as source}<option value={source.artifact_id}>{source.display_name}</option>{/each}</select>{#if selectedRun&&['queued','running'].includes(selectedRun.status)}<button onclick={cancel} class="action text-red-500"><Square size={15}/> Stop</button>{:else}<button onclick={run} disabled={!selectedSource} class="action bg-[var(--accent)] text-white disabled:opacity-40"><Play size={15}/> Run cleaning</button>{/if}</div></div>{#if error}<p class="text-sm text-red-500">{error}</p>{/if}<SettingsPanel {sessionId} section="source_cleaning" title="Extraction and agentic loop"/><div class="grid gap-5 lg:grid-cols-[18rem_1fr]"><aside class="surface rounded-2xl p-4"><div class="eyebrow mb-3">Runs</div>{#each runs as item}<button onclick={()=>selectRun(item)} class:active={selectedRun?.id===item.id} class="run"><strong>{item.status}</strong><span>{new Date(item.created_at).toLocaleString()}</span></button>{:else}<p class="muted text-sm">No agentic runs yet.</p>{/each}</aside><section class="surface rounded-2xl p-5"><div class="flex justify-between"><div><div class="eyebrow">Agent audit</div><p class="muted mt-2 text-sm">Phase summaries, operations, validation warnings, tool results, and costs. Chain-of-thought is never stored.</p></div>{#if selectedRun?.status==='completed'}<button onclick={accept} class="action"><Check size={14}/> Accept result</button>{/if}</div><div class="mt-5 space-y-3">{#each steps as step}<article class="rounded-xl border border-[var(--line)] p-4"><div class="flex justify-between"><strong>{step.phase}</strong><span class="muted text-xs">{step.status}</span></div><p class="muted mt-2 text-sm">{step.summary}</p>{#if step.output_json?.warnings?.length}<ul class="mt-3 list-disc pl-5 text-xs text-[var(--warning)]">{#each step.output_json.warnings as warning}<li>{warning}</li>{/each}</ul>{/if}</article>{:else}<p class="muted text-sm">Select a completed run to inspect its structured audit.</p>{/each}</div></section></div></div>
<style>.action{display:flex;align-items:center;gap:.4rem;border:1px solid var(--line);border-radius:.75rem;padding:.65rem .8rem;font-size:.78rem;font-weight:700}.run{display:block;width:100%;border-radius:.7rem;padding:.7rem;text-align:left}.run:hover,.run.active{background:var(--accent-soft)}.run strong,.run span{display:block;font-size:.72rem}.run span{margin-top:.2rem;color:var(--muted);font-weight:400}</style>
