import { apiJson } from './api';
import type { GenerationRun } from './api-models';

/** Explicit full-run generation choice shown in GenerationStartDialog. */
export type GenerationStartMode = 'continue' | 'refresh' | 'all';

export type GenerationPreviewMode = 'missing' | 'stale' | 'all';

export type GenerationPreviewReasons = {
  missing_audio: number;
  edited_or_failed: number;
  settings_changed: number;
  voice_changed: number;
  performance_changed: number;
  identity_unknown: number;
  /** Present for deliberate full regeneration: rows generated by explicit
   * choice rather than a detected change. */
  requested?: number;
};

export type GenerationPreview = {
  mode: GenerationPreviewMode;
  speech_plan_revision_id: string;
  selection_hash: string;
  total_count: number;
  generate_count: number;
  preserve_count: number;
  replace_count: number;
  missing_count: number;
  reasons: GenerationPreviewReasons;
  first_generate_ordinal: number | null;
  blocked_reason?: string | null;
  settings_summary?: {
    service: string;
    model: string;
    voice: string;
  } | null;
};

export type GenerationPreviewRequest = {
  settings_source_run_id?: string | null;
  speech_plan_revision_id: string;
  missing_only: boolean;
  stale_only: boolean;
};

export type GenerationConfirmRequest = GenerationPreviewRequest & {
  /** Preview is mandatory: starts always bind to a previewed selection. */
  expected_selection_hash: string;
};

/**
 * Map the explicit dialog choice onto the backend selection flags.
 * Continue keeps completed recordings (missing_only); refresh regenerates
 * changed-setting/unverified recordings (stale_only); all replaces everything.
 */
export function startModeFlags(mode: GenerationStartMode): {
  missing_only: boolean;
  stale_only: boolean;
} {
  if (mode === 'continue') return { missing_only: true, stale_only: false };
  if (mode === 'refresh') return { missing_only: false, stale_only: true };
  return { missing_only: false, stale_only: false };
}

export function previewModeForStartMode(
  mode: GenerationStartMode
): GenerationPreviewMode {
  if (mode === 'continue') return 'missing';
  if (mode === 'refresh') return 'stale';
  return 'all';
}

/** Read-only preflight. Never generates, never writes, never enqueues. */
export function previewGenerationStart(
  sessionId: string,
  body: GenerationPreviewRequest,
  signal?: AbortSignal
): Promise<GenerationPreview> {
  return apiJson<GenerationPreview>(
    `/api/v1/sessions/${encodeURIComponent(sessionId)}/generation-runs/preview`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ operation: 'generate', ...body }),
      signal
    }
  );
}

/**
 * Start a full-run generation bound to a previewed selection. The
 * expected_selection_hash optimism guard makes the server recompute the
 * selection and reject with 409 on any drift; callers must surface that,
 * refresh the preview, and require the user to re-confirm (never retry
 * automatically).
 */
export function confirmGenerationStart(
  sessionId: string,
  body: GenerationConfirmRequest
): Promise<GenerationRun> {
  return apiJson<GenerationRun>(
    `/api/v1/sessions/${encodeURIComponent(sessionId)}/generation-runs`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ operation: 'generate', ...body })
    }
  );
}

const REASON_LABELS: Record<keyof GenerationPreviewReasons, string> = {
  missing_audio: 'No recording yet',
  edited_or_failed: 'Edited or previously failed',
  settings_changed: 'Generation settings changed',
  voice_changed: 'Voice changed',
  performance_changed: 'Voice direction or delivery changed',
  identity_unknown: 'Saved voice/settings could not be verified',
  requested: 'Regenerated by explicit choice'
};

export function reasonLabel(reason: keyof GenerationPreviewReasons): string {
  return REASON_LABELS[reason];
}

export function nonzeroReasons(
  reasons: GenerationPreviewReasons
): { key: keyof GenerationPreviewReasons; label: string; count: number }[] {
  return (Object.keys(REASON_LABELS) as (keyof GenerationPreviewReasons)[])
    .map((key) => ({
      key,
      label: REASON_LABELS[key],
      count: reasons[key] ?? 0
    }))
    .filter((item) => item.count > 0);
}
