<script lang="ts">
  import { CheckCircle2, Plus, RefreshCw, Server, X } from '@lucide/svelte';
  import { api } from './api';
  let payload=$state<any>({services:[],profiles:[],value:{},revision:0});let discoverOpen=$state(false);let baseUrl=$state('http://127.0.0.1:8000');let discovering=$state(false);let refreshing=$state('');let result=$state<any>(null);let error=$state('');
  async function load(){payload=await api('/services/tts')}load();
  async function discover(){discovering=true;error='';try{result=await api('/services/tts/discover',{method:'POST',body:JSON.stringify({base_url:baseUrl})})}catch(caught){error=caught instanceof Error?caught.message:String(caught)}finally{discovering=false}}
  async function persist(value:any){await api('/settings/defaults.tts',{method:'PUT',headers:{'If-Match':`"${payload.revision}"`},body:JSON.stringify({value})});await load()}
  function recordFrom(candidate:any, existing:any={}){return {...existing,id:existing.id??crypto.randomUUID(),name:candidate.name,api_base:candidate.api_base,provider:candidate.provider,adapter:candidate.adapter,speech_path:candidate.speech_path,models_path:candidate.models_path,voices_path:candidate.voices_path,request_fields:candidate.request_fields,request_defaults:candidate.request_defaults,models:candidate.models??[],voices:candidate.voices??[],supports_prebuilt_voices:candidate.supports_prebuilt_voices}}
  async function saveDiscovered(){if(!result?.success)return;const existing=(payload.value.provider_configs??[]).find((item:any)=>item.api_base===result.api_base);const value={...payload.value,provider_configs:[...(payload.value.provider_configs??[]).filter((item:any)=>item.api_base!==result.api_base),recordFrom(result,existing)]};await persist(value);discoverOpen=false;result=null}
  async function useProfile(profile:any){const existing=(payload.value.provider_configs??[]).find((item:any)=>item.id===profile.id||item.api_base===profile.api_base);await persist({...payload.value,provider_configs:[...(payload.value.provider_configs??[]).filter((item:any)=>item.id!==profile.id&&item.api_base!==profile.api_base),recordFrom(profile,existing??{id:profile.id})]})}
  async function setDefault(service:any){await persist({...payload.value,service:service.id})}
  async function removeService(service:any){await persist({...payload.value,provider_configs:(payload.value.provider_configs??[]).filter((item:any)=>item.id!==service.id&&item.api_base!==service.api_base)})}
  async function refreshService(service:any){refreshing=service.id;error='';try{const found=await api<any>('/services/tts/discover',{method:'POST',body:JSON.stringify({base_url:service.api_base})});const existing=(payload.value.provider_configs??[]).find((item:any)=>item.id===service.id||item.api_base===service.api_base);if(existing)await persist({...payload.value,provider_configs:[...(payload.value.provider_configs??[]).filter((item:any)=>item.id!==existing.id),recordFrom(found,existing)]});else await load()}catch(caught){error=caught instanceof Error?caught.message:String(caught)}finally{refreshing=''}}
</script>
<section><div class="flex items-end justify-between gap-4"><div><div class="eyebrow">TTS services</div><h2 class="mt-1 text-2xl font-semibold">Speech connections</h2></div><div class="flex gap-2"><button onclick={load} class="tool"><RefreshCw size={16}/> Refresh all</button><button onclick={()=>discoverOpen=true} class="tool bg-[var(--accent)] text-white"><Plus size={16}/> Connect endpoint</button></div></div>{#if error}<p class="mt-3 text-sm text-red-500">{error}</p>{/if}<div class="mt-5 grid gap-3 md:grid-cols-2">{#each payload.services??[] as service}<article class="rounded-2xl border border-[var(--line)] p-4"><div class="flex items-center gap-3"><div class="grid size-9 place-items-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><Server size={17}/></div><div class="min-w-0 flex-1"><div class="truncate font-semibold">{service.name}</div><div class="muted truncate text-xs">{service.api_base}</div></div>{#if service.models?.length}<CheckCircle2 class="text-[var(--success)]" size={17}/>{/if}</div><div class="muted mt-3 text-xs">{service.models?.length??0} models · {service.voices?.length??0} voices</div><div class="mt-3 flex flex-wrap gap-2"><button class="tool" onclick={()=>setDefault(service)} disabled={payload.value.service===service.id}>{payload.value.service===service.id?'Default':'Make default'}</button><button class="tool" onclick={()=>refreshService(service)} disabled={refreshing===service.id}><RefreshCw size={13}/>{refreshing===service.id?'Testing…':'Test & refresh'}</button>{#if (payload.value.provider_configs??[]).some((item:any)=>item.id===service.id||item.api_base===service.api_base)}<button class="tool text-red-500" onclick={()=>removeService(service)}>Remove</button>{/if}</div></article>{/each}</div><details class="mt-6 rounded-2xl border border-[var(--line)] p-4"><summary class="cursor-pointer font-semibold">Known compatible endpoint profiles</summary><div class="mt-4 grid gap-2 md:grid-cols-2">{#each payload.profiles??[] as profile}<div class="rounded-xl border border-[var(--line)] p-3"><div class="text-sm font-semibold">{profile.name}</div><div class="muted mt-1 text-xs">{profile.description}</div><button onclick={()=>useProfile(profile)} class="tool mt-3">Use profile</button></div>{/each}</div></details></section>
{#if discoverOpen}<div class="fixed inset-0 z-50 grid place-items-center bg-black/40 p-5"><div class="surface w-full max-w-xl rounded-3xl p-7"><div class="flex justify-between"><div><div class="eyebrow">Connect TTS</div><h2 class="mt-1 text-2xl font-semibold">Discover an endpoint</h2></div><button onclick={()=>discoverOpen=false}><X size={19}/></button></div><label class="mt-6 block text-sm font-semibold">Base URL<input bind:value={baseUrl} class="mt-2 w-full rounded-xl border border-[var(--line)] bg-[var(--paper)] px-4 py-3"/></label><button onclick={discover} disabled={discovering} class="mt-4 w-full rounded-xl bg-[var(--accent)] px-4 py-3 font-semibold text-white">{discovering?'Inspecting…':'Detect API'}</button>{#if error}<p class="mt-3 text-sm text-red-500">{error}</p>{/if}{#if result}<div class="mt-5 rounded-xl border border-[var(--line)] p-4"><div class="font-semibold">{result.name}</div><p class="muted mt-2 text-sm">{result.message}</p><div class="muted mt-2 text-xs">{result.models?.length??0} models · {result.voices?.length??0} voices · {result.confidence} confidence</div><button onclick={saveDiscovered} class="mt-4 rounded-xl bg-[var(--accent)] px-4 py-2 text-sm font-semibold text-white">Save connection</button></div>{/if}</div></div>{/if}
<style>.tool{display:flex;align-items:center;gap:.45rem;border:1px solid var(--line);border-radius:.75rem;padding:.65rem .8rem;font-size:.78rem;font-weight:650}</style>
