<script lang="ts">
  import { ArrowLeft, Library, Mic, Play, Plus, Save, Square, Trash2, WandSparkles } from '@lucide/svelte';
  import { api, type JobRecord } from './api';
  import { onMount } from 'svelte';
  type Voice = { id:string; name:string; language?:string; description?:string };
  type Sample = { id:string; artifact_id:string; transcript?:string; transcript_language?:string; transcript_reviewed:boolean };
  let { onback }: { onback: () => void } = $props();
  let voices=$state<Voice[]>([]); let selected=$state<Voice|null>(null); let samples=$state<Sample[]>([]); let capabilities=$state<any>({});
  let error=$state(''); let newName=$state(''); let language=$state('en'); let backend=$state('whisperx'); let transcripts=$state<Record<string,string>>({});
  let devices=$state<MediaDeviceInfo[]>([]); let deviceId=$state(''); let recorder=$state<MediaRecorder|null>(null); let chunks:Blob[]=[]; let recording=$state(false); let seconds=$state(0); let timer:number|undefined; let recordingBlob=$state<Blob|null>(null); let recordingUrl=$state('');
  const canTranscribe=$derived(Boolean(capabilities?.stt?.whisperx || capabilities?.stt?.parakeet_onnx));
  async function loadVoices(){const result=await api<{items:Voice[]}>('/voices'); voices=result.items; if(selected) selected=voices.find(v=>v.id===selected?.id)??null;}
  async function choose(voice:Voice){selected=voice; const result=await api<{items:Sample[]}>(`/voices/${voice.id}/samples`); samples=result.items; transcripts=Object.fromEntries(samples.map(s=>[s.id,s.transcript??'']));}
  async function createVoice(){if(!newName.trim())return; try{const voice=await api<Voice>('/voices',{method:'POST',body:JSON.stringify({name:newName.trim(),language})});newName='';await loadVoices();await choose(voice);}catch(caught){error=caught instanceof Error?caught.message:String(caught)}}
  async function prepareMicrophones(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop());devices=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='audioinput');deviceId=devices[0]?.deviceId??'';}catch(caught){error=`Microphone unavailable: ${caught instanceof Error?caught.message:String(caught)}`}}
  async function startRecording(){try{discard();const stream=await navigator.mediaDevices.getUserMedia({audio:deviceId?{deviceId:{exact:deviceId}}:true});const preferred=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/webm'].find(MediaRecorder.isTypeSupported);const next=new MediaRecorder(stream,preferred?{mimeType:preferred}:undefined);chunks=[];next.ondataavailable=e=>e.data.size&&chunks.push(e.data);next.onstop=()=>{recordingBlob=new Blob(chunks,{type:next.mimeType});recordingUrl=URL.createObjectURL(recordingBlob);stream.getTracks().forEach(t=>t.stop())};next.start(250);recorder=next;recording=true;seconds=0;timer=window.setInterval(()=>seconds+=1,1000);}catch(caught){error=caught instanceof Error?caught.message:String(caught)}}
  function stopRecording(){recorder?.stop();recording=false;if(timer)clearInterval(timer);timer=undefined;}
  function discard(){if(recording)stopRecording();if(recordingUrl)URL.revokeObjectURL(recordingUrl);recordingUrl='';recordingBlob=null;chunks=[];}
  async function saveRecording(){if(!selected||!recordingBlob)return;const body=new FormData();body.set('file',recordingBlob,`recording.${recordingBlob.type.includes('ogg')?'ogg':'webm'}`);try{const job=await api<JobRecord>(`/voices/${selected.id}/samples`,{method:'POST',body});await waitJob(job.id);discard();await choose(selected);}catch(caught){error=caught instanceof Error?caught.message:String(caught)}}
  async function waitJob(id:string){for(let attempt=0;attempt<240;attempt++){const job=await api<JobRecord>(`/jobs/${id}`);if(job.status==='succeeded')return job;if(['failed','canceled'].includes(job.status))throw new Error(job.error_message||`Job ${job.status}`);await new Promise(resolve=>setTimeout(resolve,500));}throw new Error('The operation is still running. Check the job queue.')}
  async function transcribe(sample:Sample){if(!selected)return;try{const job=await api<JobRecord>(`/voices/${selected.id}/samples/${sample.id}/transcribe`,{method:'POST',body:JSON.stringify({backend,language})});const completed=await waitJob(job.id);transcripts[sample.id]=String(completed.result_json?.transcript??'');}catch(caught){error=caught instanceof Error?caught.message:String(caught)}}
  async function transcribeMissing(){for(const sample of samples.filter(s=>!s.transcript_reviewed))await transcribe(sample)}
  async function saveTranscript(sample:Sample){if(!selected||!transcripts[sample.id]?.trim())return;try{await api(`/voices/${selected.id}/samples/${sample.id}/transcript`,{method:'PATCH',body:JSON.stringify({transcript:transcripts[sample.id].trim(),language})});await choose(selected);}catch(caught){error=caught instanceof Error?caught.message:String(caught)}}
  onMount(async()=>{try{[capabilities]=await Promise.all([api('/capabilities'),loadVoices()]);await prepareMicrophones();}catch(caught){error=caught instanceof Error?caught.message:String(caught)}})
</script>

<div class="mx-auto flex min-h-[calc(100vh-5rem)] max-w-7xl flex-col"><button onclick={onback} class="muted mb-6 flex items-center gap-2 self-start text-sm font-semibold"><ArrowLeft size={17}/> Workspace</button><header class="mb-6"><div class="eyebrow">Voice library</div><h1 class="mt-2 text-4xl font-semibold">Reference voices</h1></header>{#if error}<div class="mb-4 rounded-xl border border-red-400/40 bg-red-500/10 px-4 py-3 text-sm">{error}</div>{/if}
  <div class="grid min-h-0 flex-1 gap-5 lg:grid-cols-[20rem_1fr]"><aside class="surface flex min-h-0 flex-col rounded-3xl p-4"><div class="flex gap-2"><input bind:value={newName} placeholder="New voice" class="min-w-0 flex-1 rounded-xl border border-[var(--line)] bg-[var(--paper)] px-3 py-2 text-sm"/><button onclick={createVoice} aria-label="Add voice" class="rounded-xl bg-[var(--accent)] p-2.5 text-white"><Plus size={17}/></button></div><div class="mt-4 min-h-0 flex-1 space-y-1 overflow-auto">{#each voices as voice}<button onclick={()=>choose(voice)} class:active={selected?.id===voice.id} class="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left"><Library size={17}/><span class="min-w-0 flex-1 truncate font-semibold">{voice.name}</span><span class="muted text-xs">{voice.language}</span></button>{:else}<p class="muted p-5 text-center text-sm">Create a voice to add samples.</p>{/each}</div></aside>
    <main class="surface min-h-0 overflow-auto rounded-3xl p-5 sm:p-7">{#if selected}<div class="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h2 class="text-2xl font-semibold">{selected.name}</h2><p class="muted text-sm">Review playback, transcripts, and recordings in one place.</p></div><div class="flex gap-2"><select bind:value={backend} disabled={!canTranscribe} class="rounded-xl border border-[var(--line)] bg-[var(--paper)] px-3 py-2 text-sm"><option value="whisperx">WhisperX</option><option value="parakeet_onnx">ONNX Parakeet</option></select><button onclick={transcribeMissing} disabled={!canTranscribe} class="flex items-center gap-2 rounded-xl border border-[var(--line)] px-3 py-2 text-sm font-semibold disabled:opacity-40"><WandSparkles size={16}/> Transcribe missing</button></div></div>
      <section class="mb-7 rounded-2xl border border-[var(--line)] p-4"><div class="flex flex-wrap items-center gap-3"><select bind:value={deviceId} disabled={!devices.length||recording} class="min-w-48 rounded-xl border border-[var(--line)] bg-[var(--paper)] px-3 py-2 text-sm">{#each devices as device}<option value={device.deviceId}>{device.label||'Microphone'}</option>{/each}</select>{#if !recording}<button onclick={startRecording} disabled={!devices.length||!capabilities?.ffmpeg?.available} class="flex items-center gap-2 rounded-xl bg-red-500 px-4 py-2 font-semibold text-white disabled:opacity-40"><Mic size={16}/> Record</button>{:else}<button onclick={stopRecording} class="flex items-center gap-2 rounded-xl bg-red-500 px-4 py-2 font-semibold text-white"><Square size={15}/> Stop · {seconds}s</button>{/if}{#if recordingUrl}<audio controls src={recordingUrl} class="h-9 min-w-56 flex-1"></audio><button onclick={discard} class="rounded-xl border border-[var(--line)] p-2"><Trash2 size={16}/></button><button onclick={saveRecording} class="flex items-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-2 font-semibold text-white"><Save size={16}/> Save sample</button>{/if}</div>{#if !capabilities?.ffmpeg?.available}<p class="mt-2 text-xs text-[var(--warning)]">Recording is disabled until FFmpeg is available.</p>{/if}</section>
      <div class="space-y-4">{#each samples as sample}<article class="rounded-2xl border border-[var(--line)] p-4"><div class="flex flex-wrap items-center gap-3"><audio controls src={`/api/v1/artifacts/${sample.artifact_id}/content`} class="h-9 min-w-64 flex-1"></audio><button onclick={()=>transcribe(sample)} disabled={!canTranscribe} class="flex items-center gap-2 rounded-xl border border-[var(--line)] px-3 py-2 text-sm font-semibold disabled:opacity-40"><WandSparkles size={15}/> Transcribe</button></div><textarea bind:value={transcripts[sample.id]} rows="3" placeholder="Transcript will remain unsaved until you review it." class="mt-3 w-full rounded-xl border border-[var(--line)] bg-[var(--paper)] p-3 text-sm"></textarea><div class="mt-2 flex justify-end"><button onclick={()=>saveTranscript(sample)} disabled={!transcripts[sample.id]?.trim()} class="flex items-center gap-2 rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-white disabled:opacity-40"><Save size={14}/> Save reviewed transcript</button></div></article>{:else}<div class="muted rounded-2xl border border-dashed border-[var(--line)] p-10 text-center"><Play class="mx-auto mb-2" size={22}/> Record the first sample above.</div>{/each}</div>
    {:else}<div class="grid h-full min-h-96 place-items-center text-center"><div><Library class="mx-auto text-[var(--accent)]" size={30}/><h2 class="mt-3 text-xl font-semibold">Select a voice</h2><p class="muted mt-1">Or create one in the left panel.</p></div></div>{/if}</main></div>
</div>
<style>aside button.active{background:var(--accent-soft);color:var(--accent)}</style>
