/** The same varied audition passage in every supported design language. */
export const VOICE_DESIGN_SAMPLES: Record<string, string> = {
  en: 'Morning light filled the room as we opened the window and listened to the city wake up. Somewhere outside, a bicycle bell rang, and a neighbor called a cheerful greeting. “Shall we begin?” she asked. There was no need to hurry. We had a clear plan, a little curiosity, and enough time to do the work carefully.',
  de: 'Morgenlicht erfüllte den Raum, als wir das Fenster öffneten und der erwachenden Stadt lauschten. Irgendwo draußen klingelte ein Fahrrad, und eine Nachbarin rief uns fröhlich einen Gruß zu. „Sollen wir anfangen?“, fragte sie. Es gab keinen Grund zur Eile. Wir hatten einen klaren Plan, ein wenig Neugier und genug Zeit, um die Arbeit sorgfältig zu erledigen.',
  fr: 'La lumière du matin remplissait la pièce tandis que nous ouvrions la fenêtre pour écouter la ville se réveiller. Dehors, une sonnette de vélo a retenti, et une voisine nous a salués joyeusement. « On commence ? » a-t-elle demandé. Rien ne pressait. Nous avions un plan clair, un peu de curiosité et assez de temps pour travailler avec soin.',
  es: 'La luz de la mañana llenó la habitación cuando abrimos la ventana y escuchamos cómo despertaba la ciudad. Afuera sonó el timbre de una bicicleta y una vecina nos saludó con alegría. «¿Empezamos?», preguntó. No había ninguna prisa. Teníamos un plan claro, un poco de curiosidad y tiempo suficiente para hacer el trabajo con cuidado.',
  it: 'La luce del mattino riempiva la stanza mentre aprivamo la finestra e ascoltavamo la città svegliarsi. Fuori suonò il campanello di una bicicletta e una vicina ci salutò allegramente. «Cominciamo?», chiese. Non c’era bisogno di avere fretta. Avevamo un piano chiaro, un po’ di curiosità e abbastanza tempo per fare il lavoro con cura.',
  pt: 'A luz da manhã enchia o quarto quando abrimos a janela e ouvimos a cidade despertar. Lá fora, soou a campainha de uma bicicleta, e uma vizinha nos cumprimentou com alegria. “Vamos começar?”, perguntou ela. Não havia motivo para pressa. Tínhamos um plano claro, um pouco de curiosidade e tempo suficiente para fazer o trabalho com cuidado.',
  ru: 'Утренний свет наполнил комнату, когда мы открыли окно и прислушались к пробуждающемуся городу. Где-то на улице прозвенел велосипедный звонок, и соседка весело поздоровалась с нами. «Ну что, начнём?» — спросила она. Торопиться было незачем. У нас был ясный план, немного любопытства и достаточно времени, чтобы выполнить работу внимательно и аккуратно.',
  zh: '我们打开窗户，听着城市渐渐苏醒，清晨的阳光洒满了房间。外面不知哪里传来一阵自行车铃声，一位邻居愉快地向我们打招呼。“我们开始吧？”她问道。其实没有必要着急。我们已经有了清晰的计划，带着一点好奇心，也有足够的时间，可以认真仔细地把工作做好。',
  ja: '窓を開けて街が目覚める音に耳を傾けると、朝の光が部屋いっぱいに広がりました。外のどこかで自転車のベルが鳴り、近所の人が明るく挨拶してくれました。「そろそろ始めましょうか」と彼女は言いました。急ぐ必要はありません。私たちには、はっきりした計画と少しの好奇心、そして丁寧に仕事を進めるための十分な時間がありました。',
  ko: '창문을 열고 도시가 깨어나는 소리에 귀를 기울이자 아침 햇살이 방 안을 가득 채웠습니다. 밖에서는 어디선가 자전거 벨이 울렸고, 이웃이 밝은 목소리로 인사를 건넸습니다. “이제 시작할까요?” 그녀가 물었습니다. 서두를 필요는 없었습니다. 우리에게는 분명한 계획과 약간의 호기심, 그리고 일을 꼼꼼하게 마무리할 충분한 시간이 있었습니다.'
};
