"""Presentation metadata for speech engines offered by the installer.

Keep this catalogue independent from Qt so language and capability claims can be
covered by tests and updated without rewriting the installer layout.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BackendPresentation:
    summary: str
    languages: tuple[str, ...]
    voice_cloning: bool
    prebuilt_voices: bool
    note: str
    source_url: str

    @property
    def formatted_languages(self) -> str:
        return ", ".join(self.languages) + "."


TTS_BACKENDS: dict[str, BackendPresentation] = {
    "kokoro": BackendPresentation(
        summary="Fast, lightweight multilingual speech with a broad built-in voice catalogue.",
        languages=(
            "English (US)",
            "English (UK)",
            "Spanish",
            "French",
            "Hindi",
            "Italian",
            "Japanese",
            "Brazilian Portuguese",
            "Mandarin Chinese",
        ),
        voice_cloning=False,
        prebuilt_voices=True,
        note="CPU-friendly, with CUDA, experimental ROCm, and Apple Silicon paths supported by the upstream service.",
        source_url="https://github.com/remsky/Kokoro-FastAPI",
    ),
    "kobold_qwen": BackendPresentation(
        summary="Flexible local speech through KoboldCpp, with small and high-capacity model choices.",
        languages=(
            "Chinese",
            "English",
            "Japanese",
            "Korean",
            "German",
            "French",
            "Russian",
            "Portuguese",
            "Spanish",
            "Italian",
        ),
        voice_cloning=True,
        prebuilt_voices=True,
        note="Base models clone reference audio. The CustomVoice model supplies named built-in speakers; model size, quantization, and compute backend are configurable.",
        source_url="https://huggingface.co/Qwen/Qwen3-TTS-12Hz-1.7B-Base",
    ),
    "xtts": BackendPresentation(
        summary="Mature multilingual speech generation from short reference recordings.",
        languages=(
            "English",
            "Spanish",
            "French",
            "German",
            "Italian",
            "Portuguese",
            "Polish",
            "Turkish",
            "Russian",
            "Dutch",
            "Czech",
            "Arabic",
            "Chinese",
            "Japanese",
            "Hungarian",
            "Korean",
        ),
        voice_cloning=True,
        prebuilt_voices=False,
        note="Cross-language cloning is supported. GPU generation is considerably faster; CPU mode is available for compatibility.",
        source_url="https://github.com/coqui-ai/TTS/blob/dev/docs/source/models/xtts.md",
    ),
    "voxcpm": BackendPresentation(
        summary="High-fidelity multilingual speech conditioned by an uploaded reference voice.",
        languages=(
            "Arabic",
            "Burmese",
            "Chinese",
            "Danish",
            "Dutch",
            "English",
            "Finnish",
            "French",
            "German",
            "Greek",
            "Hebrew",
            "Hindi",
            "Indonesian",
            "Italian",
            "Japanese",
            "Khmer",
            "Korean",
            "Lao",
            "Malay",
            "Norwegian",
            "Polish",
            "Portuguese",
            "Russian",
            "Spanish",
            "Swahili",
            "Swedish",
            "Tagalog",
            "Thai",
            "Turkish",
            "Vietnamese",
        ),
        voice_cloning=True,
        prebuilt_voices=False,
        note="VoxCPM2 also supports several Chinese dialects. It is a comparatively large model intended for capable CUDA hardware.",
        source_url="https://huggingface.co/openbmb/VoxCPM2",
    ),
    "fishs2": BackendPresentation(
        summary="Expressive, broad-language synthesis and rapid cloning through the native S2 runtime.",
        languages=(
            "Japanese",
            "English",
            "Chinese",
            "Korean",
            "Spanish",
            "Portuguese",
            "Arabic",
            "Russian",
            "French",
            "German",
            "Swedish",
            "Italian",
            "Turkish",
            "Norwegian",
            "Dutch",
            "Welsh",
            "Basque",
            "Catalan",
            "Danish",
            "Galician",
            "Tamil",
            "Hungarian",
            "Finnish",
            "Polish",
            "Estonian",
            "Hindi",
            "Latin",
            "Urdu",
            "Thai",
            "Vietnamese",
            "Javanese",
            "Bengali",
            "Yoruba",
            "South Slavey",
            "Czech",
            "Swahili",
            "Norwegian Nynorsk",
            "Hebrew",
            "Malay",
            "Ukrainian",
            "Indonesian",
            "Kazakh",
            "Bulgarian",
            "Latvian",
            "Burmese",
            "Tagalog",
            "Slovak",
            "Nepali",
            "Persian",
            "Afrikaans",
            "Greek",
            "Tibetan",
            "Croatian",
            "Romanian",
            "Shona",
            "Maori",
            "Yiddish",
            "Amharic",
            "Belarusian",
            "Khmer",
            "Icelandic",
            "Azerbaijani",
            "Sindhi",
            "Breton",
            "Albanian",
            "Pashto",
            "Mongolian",
            "Haitian Creole",
            "Malayalam",
            "Serbian",
            "Sanskrit",
            "Telugu",
            "Georgian",
            "Bosnian",
            "Punjabi",
            "Lithuanian",
            "Kannada",
            "Sinhala",
            "Armenian",
            "Marathi",
            "Assamese",
            "Gujarati",
            "Faroese",
        ),
        voice_cloning=True,
        prebuilt_voices=False,
        note="Japanese, English, and Chinese are the highest-support tier. Quantization and compute backend are selectable during setup.",
        source_url="https://github.com/fishaudio/fish-speech",
    ),
    "voxtral": BackendPresentation(
        summary="GPU speech generation with a curated catalogue of preset voices.",
        languages=(
            "Arabic",
            "English",
            "German",
            "Spanish",
            "French",
            "Hindi",
            "Italian",
            "Dutch",
            "Portuguese",
        ),
        voice_cloning=False,
        prebuilt_voices=True,
        note="The packaged service uses preset speakers and a WGPU-compatible accelerator on Windows and Linux; it does not provide a CPU path.",
        source_url="https://github.com/lukaszliniewicz/voxtral-fastapi",
    ),
    "silero": BackendPresentation(
        summary="A small, CPU-friendly engine with language-specific preset speakers.",
        languages=(
            "German",
            "English",
            "English (Indic model)",
            "Spanish",
            "French",
            "Hindi and Indic languages",
            "Russian",
            "Tatar",
            "Ukrainian",
            "Uzbek",
            "Kalmyk",
        ),
        voice_cloning=False,
        prebuilt_voices=True,
        note="Legacy integration. Its upstream API server currently has incompatible dependencies and a broken language catalogue, so Linux installation is disabled.",
        source_url="https://github.com/snakers4/silero-models",
    ),
    "chatterbox": BackendPresentation(
        summary="Expressive, cross-language speech generated from a reference recording.",
        languages=(
            "Arabic",
            "Danish",
            "German",
            "Greek",
            "English",
            "Spanish",
            "Finnish",
            "French",
            "Hebrew",
            "Hindi",
            "Italian",
            "Japanese",
            "Korean",
            "Malay",
            "Dutch",
            "Norwegian",
            "Polish",
            "Portuguese",
            "Russian",
            "Swedish",
            "Swahili",
            "Turkish",
            "Chinese",
        ),
        voice_cloning=True,
        prebuilt_voices=False,
        note="The multilingual model supports 23 languages. CUDA is recommended for interactive generation; CPU mode is available but slower.",
        source_url="https://github.com/resemble-ai/chatterbox",
    ),
    "magpie": BackendPresentation(
        summary="A multilingual local service with five expressive preset speakers.",
        languages=(
            "English",
            "Spanish",
            "German",
            "French",
            "Vietnamese",
            "Italian",
            "Mandarin Chinese",
            "Hindi",
            "Japanese",
        ),
        voice_cloning=False,
        prebuilt_voices=True,
        note="All five speakers can speak every supported language. CPU and NVIDIA CUDA runtimes are available on Windows and Linux; the first NeMo installation is comparatively large.",
        source_url="https://huggingface.co/nvidia/magpie_tts_multilingual_357m",
    ),
}


TTS_BACKEND_ORDER = (
    "kokoro",
    "kobold_qwen",
    "xtts",
    "voxcpm",
    "fishs2",
    "voxtral",
    "silero",
    "chatterbox",
    "magpie",
)


WHISPER_LARGE_V3_LANGUAGES = (
    "English", "Chinese", "German", "Spanish", "Russian", "Korean", "French",
    "Japanese", "Portuguese", "Turkish", "Polish", "Catalan", "Dutch", "Arabic",
    "Swedish", "Italian", "Indonesian", "Hindi", "Finnish", "Vietnamese", "Hebrew",
    "Ukrainian", "Greek", "Malay", "Czech", "Romanian", "Danish", "Hungarian",
    "Tamil", "Norwegian", "Thai", "Urdu", "Croatian", "Bulgarian", "Lithuanian",
    "Latin", "Maori", "Malayalam", "Welsh", "Slovak", "Telugu", "Persian",
    "Latvian", "Bengali", "Serbian", "Azerbaijani", "Slovenian", "Kannada",
    "Estonian", "Macedonian", "Breton", "Basque", "Icelandic", "Armenian", "Nepali",
    "Mongolian", "Bosnian", "Kazakh", "Albanian", "Swahili", "Galician", "Marathi",
    "Punjabi", "Sinhala", "Khmer", "Shona", "Yoruba", "Somali", "Afrikaans",
    "Occitan", "Georgian", "Belarusian", "Tajik", "Sindhi", "Gujarati", "Amharic",
    "Yiddish", "Lao", "Uzbek", "Faroese", "Haitian Creole", "Pashto", "Turkmen",
    "Nynorsk", "Maltese", "Sanskrit", "Luxembourgish", "Myanmar", "Tibetan",
    "Tagalog", "Malagasy", "Assamese", "Tatar", "Hawaiian", "Lingala", "Hausa",
    "Bashkir", "Javanese", "Sundanese", "Cantonese",
)

PARAKEET_06B_V3_LANGUAGES = (
    "Bulgarian", "Croatian", "Czech", "Danish", "Dutch", "English", "Estonian",
    "Finnish", "French", "German", "Greek", "Hungarian", "Italian", "Latvian",
    "Lithuanian", "Maltese", "Polish", "Portuguese", "Romanian", "Slovak",
    "Slovenian", "Spanish", "Swedish", "Russian", "Ukrainian",
)


def formatted_crispasr_languages() -> str:
    whisper = ", ".join(WHISPER_LARGE_V3_LANGUAGES)
    parakeet = ", ".join(PARAKEET_06B_V3_LANGUAGES)
    return (
        f"Whisper large-v3 (100): {whisper}.\n\n"
        f"Parakeet TDT 0.6B v3 (25): {parakeet}."
    )
