"""Static contracts for installer host operation and storage peers."""

from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

ConcurrentTask = (
    Callable[..., object] | tuple[Callable[..., object], tuple[object, ...], dict[str, object]]
)


class OperationsProvider(Protocol):
    def initialize_logging(self) -> None: ...
    def shutdown_logging(self) -> None: ...
    def show_calibre_installation_message(self) -> None: ...
    def is_admin(self) -> bool: ...
    def install_dependencies(
        self, pandrator_path: str, allow_system_install: bool = True
    ) -> bool: ...
    def ensure_bundled_ffmpeg_with_subtitles(self, pandrator_path: str) -> bool: ...
    def install_pytorch_for_xtts_finetuning(self, pandrator_path: str, env_name: str) -> None: ...
    def resolve_espeak_paths(self) -> tuple[str, str]: ...
    def install_espeak_ng_direct(self, pandrator_path: str | None = None) -> bool: ...


class StorageProvider(Protocol):
    def load_install_config(
        self, pandrator_path: str, detect_rvc: bool = False
    ) -> dict[str, object]: ...
    def save_install_config(self, pandrator_path: str, config: dict[str, object]) -> None: ...
    def write_packaging_layout(self, pandrator_path: str) -> None: ...
    def execute_concurrently(
        self, tasks: dict[str, ConcurrentTask], max_workers: int = 8
    ) -> dict[str, object]: ...
