import { expect, test, type Page } from '@playwright/test';
import {
  nonzeroReasons,
  previewModeForStartMode,
  reasonLabel,
  startModeFlags
} from '../src/lib/generation-start';

test('start mode flags map the explicit choice onto backend selection flags', () => {
  expect(startModeFlags('continue')).toEqual({
    missing_only: true,
    stale_only: false
  });
  expect(startModeFlags('refresh')).toEqual({
    missing_only: false,
    stale_only: true
  });
  expect(startModeFlags('all')).toEqual({
    missing_only: false,
    stale_only: false
  });
  expect(previewModeForStartMode('continue')).toBe('missing');
  expect(previewModeForStartMode('refresh')).toBe('stale');
  expect(previewModeForStartMode('all')).toBe('all');
});

test('reason labels use user-facing wording', () => {
  expect(reasonLabel('identity_unknown')).toBe(
    'Saved voice/settings could not be verified'
  );
  expect(reasonLabel('performance_changed')).toBe(
    'Voice direction or delivery changed'
  );
  expect(reasonLabel('missing_audio')).toBe('No recording yet');
  expect(reasonLabel('edited_or_failed')).toBe('Edited or previously failed');
});

test('nonzero reasons keep only observed buckets including deliberate-all', () => {
  expect(
    nonzeroReasons({
      missing_audio: 0,
      edited_or_failed: 2,
      settings_changed: 0,
      voice_changed: 0,
      performance_changed: 0,
      identity_unknown: 1
    }).map((item) => [item.key, item.count])
  ).toEqual([
    ['edited_or_failed', 2],
    ['identity_unknown', 1]
  ]);
  expect(
    nonzeroReasons({
      missing_audio: 0,
      edited_or_failed: 0,
      settings_changed: 0,
      voice_changed: 0,
      performance_changed: 0,
      identity_unknown: 0,
      requested: 5
    }).map((item) => [item.key, item.label])
  ).toEqual([['requested', 'Regenerated by explicit choice']]);
});

type PreviewBody = {
  operation: string;
  speech_plan_revision_id: string;
  missing_only: boolean;
  stale_only: boolean;
};

const BASE_REASONS = {
  missing_audio: 0,
  edited_or_failed: 0,
  settings_changed: 0,
  voice_changed: 0,
  performance_changed: 0,
  identity_unknown: 0
};

function previewPayload(
  revisionId: string,
  hash: string,
  overrides: Record<string, unknown>
) {
  return {
    speech_plan_revision_id: revisionId,
    selection_hash: hash,
    settings_summary: { service: 'XTTS', model: 'xtts-v2', voice: 'Narrator' },
    ...overrides
  };
}

function previewsFor(revisionId: string, hash = 'hash-missing') {
  return {
    missing: previewPayload(revisionId, hash, {
      mode: 'missing',
      total_count: 5,
      generate_count: 1,
      preserve_count: 4,
      replace_count: 1,
      missing_count: 0,
      reasons: { ...BASE_REASONS, edited_or_failed: 1 },
      first_generate_ordinal: 2
    }),
    stale: previewPayload(revisionId, 'hash-stale', {
      mode: 'stale',
      total_count: 5,
      generate_count: 3,
      preserve_count: 2,
      replace_count: 2,
      missing_count: 1,
      reasons: {
        ...BASE_REASONS,
        settings_changed: 1,
        voice_changed: 1,
        identity_unknown: 1
      },
      first_generate_ordinal: 0
    }),
    all: previewPayload(revisionId, 'hash-all', {
      mode: 'all',
      total_count: 5,
      generate_count: 5,
      preserve_count: 0,
      replace_count: 5,
      missing_count: 1,
      reasons: { ...BASE_REASONS, requested: 5 },
      first_generate_ordinal: 0
    })
  };
}

async function setupSession(page: Page) {
  await page.goto('/');
  await page.getByLabel('Owner password').fill('pandrator-e2e');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.locator('.app-shell')).toBeVisible();
  const tour = page.getByRole('button', { name: 'Close tour' });
  if (await tour.isVisible()) await tour.click();
  const csrf = (await (await page.request.get('/api/v1/auth/status')).json())
    .csrf_token as string;
  const headers = { 'X-CSRF-Token': csrf };
  const session = await (
    await page.request.post('/api/v1/sessions', {
      headers,
      data: {
        name: `Generation start ${crypto.randomUUID()}`,
        workflow_kind: 'audiobook'
      }
    })
  ).json();
  const sessionId = session.id as string;
  await page.request.post(`/api/v1/sessions/${sessionId}/generation-plan`, {
    headers,
    data: {
      segments: [
        { text: 'First block of the book.' },
        { text: 'Second block of the book.' },
        { text: 'Third block of the book.' },
        { text: 'Fourth block of the book.' },
        { text: 'Fifth block of the book.' }
      ]
    }
  });
  const listed = await page.request.get(
    `/api/v1/sessions/${sessionId}/generation-segments?limit=250`
  );
  const revisionId = (await listed.json()).plan_revision_id as string;
  expect(revisionId).toBeTruthy();
  return { sessionId, revisionId };
}

async function mockPreview(
  page: Page,
  sessionId: string,
  impl: (body: PreviewBody) => unknown
) {
  const seen: PreviewBody[] = [];
  await page.route(
    `**/api/v1/sessions/${sessionId}/generation-runs/preview`,
    async (route) => {
      const body = route.request().postDataJSON() as PreviewBody;
      seen.push(body);
      await route.fulfill({ json: (await impl(body)) as object });
    }
  );
  return seen;
}

async function mockStart(
  page: Page,
  sessionId: string,
  impl: (
    body: Record<string, unknown>,
    call: number
  ) => {
    status: number;
    json: unknown;
  }
) {
  const seen: Record<string, unknown>[] = [];
  await page.route(
    `**/api/v1/sessions/${sessionId}/generation-runs`,
    async (route) => {
      if (route.request().method() !== 'POST') return route.continue();
      const body = route.request().postDataJSON() as Record<string, unknown>;
      seen.push(body);
      const result = impl(body, seen.length);
      await route.fulfill({ status: result.status, json: result.json });
    }
  );
  return seen;
}

function startedRun(sessionId: string, revisionId: string) {
  return {
    id: 'run-new',
    session_id: sessionId,
    plan_revision_id: revisionId,
    sequence_number: 1,
    operation: 'generate',
    label: 'Run 1',
    status: 'queued',
    progress: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  };
}

async function openDialog(page: Page) {
  await page
    .locator('.generation-drawer')
    .getByRole('button', { name: 'Generate audio…', exact: true })
    .click();
  const dialog = page.getByTestId('generation-start-dialog');
  await expect(dialog).toBeVisible();
  return dialog;
}

test('continue keeps completed recordings and confirms a single block', async ({
  page
}) => {
  const { sessionId, revisionId } = await setupSession(page);
  const canned = previewsFor(revisionId);
  const previewed = await mockPreview(page, sessionId, (body) => {
    expect(body.operation).toBe('generate');
    expect(body.speech_plan_revision_id).toBe(revisionId);
    if (body.missing_only) return canned.missing;
    if (body.stale_only) return canned.stale;
    return canned.all;
  });
  const started = await mockStart(page, sessionId, () => ({
    status: 202,
    json: startedRun(sessionId, revisionId)
  }));
  await page.goto(`/sessions/${sessionId}`);
  const dialog = await openDialog(page);
  await expect(
    dialog.getByTestId('generation-start-mode-continue')
  ).toBeChecked();
  await expect(dialog.getByTestId('generation-start-counts')).toContainText(
    '5 blocks total · 1 to generate · 4 kept'
  );
  await expect(dialog.getByTestId('generation-start-reasons')).toContainText(
    'Edited or previously failed: 1'
  );
  await expect(dialog.getByTestId('generation-start-first')).toContainText(
    'First block to generate: block 3'
  );
  await expect(dialog.getByTestId('generation-start-settings')).toContainText(
    'XTTS'
  );
  // Continue reconstructs the edited block with the count-labelled confirm;
  // no replacement acknowledgment checkbox is offered for this choice.
  await expect(dialog.getByTestId('generation-start-ack')).toHaveCount(0);
  const submit = dialog.getByTestId('generation-start-submit');
  await expect(submit).toHaveText('Generate 1 block');
  await expect(submit).toBeEnabled();
  await page.screenshot({
    path: test.info().outputPath('pandrator-generation-start-dialog.png')
  });
  await submit.click();
  expect(started).toHaveLength(1);
  expect(started[0]).toMatchObject({
    operation: 'generate',
    speech_plan_revision_id: revisionId,
    missing_only: true,
    stale_only: false,
    expected_selection_hash: 'hash-missing'
  });
  await expect(dialog).toBeHidden();
  // The drawer reports what was queued and what was kept, so progress
  // starting at zero is not mistaken for regenerating the whole book.
  await expect(
    page.getByText('Queued 1 block; keeping 4 recordings.')
  ).toBeVisible();
  expect(previewed.length).toBeGreaterThanOrEqual(1);
});

test('refresh explains changed and unverified audio and needs acknowledgment', async ({
  page
}) => {
  const { sessionId, revisionId } = await setupSession(page);
  const canned = previewsFor(revisionId);
  await mockPreview(page, sessionId, (body) => {
    if (body.missing_only) return canned.missing;
    if (body.stale_only) return canned.stale;
    return canned.all;
  });
  const started = await mockStart(page, sessionId, () => ({
    status: 202,
    json: startedRun(sessionId, revisionId)
  }));
  await page.goto(`/sessions/${sessionId}`);
  const dialog = await openDialog(page);
  await dialog.getByTestId('generation-start-mode-refresh').check();
  const reasons = dialog.getByTestId('generation-start-reasons');
  await expect(reasons).toContainText('Generation settings changed: 1');
  await expect(reasons).toContainText('Voice changed: 1');
  await expect(reasons).toContainText(
    'Saved voice/settings could not be verified: 1'
  );
  await expect(dialog.getByTestId('generation-start-warning')).toContainText(
    'replaces 2 existing recordings'
  );
  const submit = dialog.getByTestId('generation-start-submit');
  await expect(submit).toHaveText('Generate 3 blocks');
  await expect(submit).toBeDisabled();
  await dialog.getByTestId('generation-start-ack').check();
  await expect(submit).toBeEnabled();
  await submit.click();
  expect(started).toHaveLength(1);
  expect(started[0]).toMatchObject({
    missing_only: false,
    stale_only: true,
    expected_selection_hash: 'hash-stale'
  });
  await expect(dialog).toBeHidden();
});

test('zero pending blocks is a noop with a disabled confirm', async ({
  page
}) => {
  const { sessionId, revisionId } = await setupSession(page);
  await mockPreview(page, sessionId, () =>
    previewPayload(revisionId, 'hash-empty', {
      mode: 'missing',
      total_count: 5,
      generate_count: 0,
      preserve_count: 5,
      replace_count: 0,
      missing_count: 0,
      reasons: { ...BASE_REASONS },
      first_generate_ordinal: null,
      blocked_reason: 'No missing blocks. Everything is already recorded.'
    })
  );
  const started = await mockStart(page, sessionId, () => ({
    status: 202,
    json: startedRun(sessionId, revisionId)
  }));
  await page.goto(`/sessions/${sessionId}`);
  const dialog = await openDialog(page);
  await expect(dialog.getByTestId('generation-start-noop')).toContainText(
    'No missing blocks. Everything is already recorded.'
  );
  const submit = dialog.getByTestId('generation-start-submit');
  await expect(submit).toHaveText('Nothing to generate');
  await expect(submit).toBeDisabled();
  expect(started).toHaveLength(0);
});

test('a slow stale preview never overrides the current choice', async ({
  page
}) => {
  const { sessionId, revisionId } = await setupSession(page);
  const canned = previewsFor(revisionId);
  const requested: string[] = [];
  await mockPreview(page, sessionId, async (body) => {
    if (body.stale_only) {
      requested.push('stale');
      await new Promise((resolve) => setTimeout(resolve, 400));
      return canned.stale;
    }
    requested.push('missing');
    return canned.missing;
  });
  await mockStart(page, sessionId, () => ({
    status: 202,
    json: startedRun(sessionId, revisionId)
  }));
  await page.goto(`/sessions/${sessionId}`);
  const dialog = await openDialog(page);
  await expect(dialog.getByTestId('generation-start-counts')).toContainText(
    '4 kept'
  );
  await dialog.getByTestId('generation-start-mode-refresh').check();
  // Mode radios stay usable during a slow refresh: switch straight back.
  await dialog.getByTestId('generation-start-mode-continue').check();
  await expect(dialog.getByTestId('generation-start-counts')).toContainText(
    '5 blocks total · 1 to generate · 4 kept'
  );
  await expect(
    dialog.getByTestId('generation-start-mode-continue')
  ).toBeChecked();
  await expect(dialog.getByTestId('generation-start-submit')).toBeEnabled();
  expect(requested).toContain('stale');
});

test('a 409 keeps its explanation and needs a new explicit click', async ({
  page
}) => {
  const { sessionId, revisionId } = await setupSession(page);
  let hash = 'hash-missing';
  await mockPreview(
    page,
    sessionId,
    () => previewsFor(revisionId, hash).missing
  );
  const started = await mockStart(page, sessionId, (_body, call) => {
    if (call === 1) {
      // The selection drifts before the next preview: no silent retry.
      hash = 'hash-missing-2';
      return {
        status: 409,
        json: {
          error: {
            code: 'generation_unavailable',
            message:
              'The selection changed while starting. Review and confirm again.'
          }
        }
      };
    }
    return { status: 202, json: startedRun(sessionId, revisionId) };
  });
  await page.goto(`/sessions/${sessionId}`);
  const dialog = await openDialog(page);
  const submit = dialog.getByTestId('generation-start-submit');
  await submit.click();
  const submitError = dialog.getByTestId('generation-start-submit-error');
  await expect(submitError).toContainText('The selection changed');
  await expect(submitError).toContainText('confirm again to start');
  expect(started).toHaveLength(1);
  // The refreshed preview requires a new explicit click with the new hash.
  await expect(submit).toBeEnabled();
  await submit.click();
  expect(started).toHaveLength(2);
  expect(started[1]).toMatchObject({
    expected_selection_hash: 'hash-missing-2'
  });
  await expect(dialog).toBeHidden();
  await page.waitForTimeout(300);
  expect(started).toHaveLength(2);
});

test('a paused run stays distinct from starting a new run', async ({
  page
}) => {
  const { sessionId, revisionId } = await setupSession(page);
  const canned = previewsFor(revisionId);
  await mockPreview(page, sessionId, () => canned.missing);
  await page.route(
    `**/api/v1/sessions/${sessionId}/generation-runs`,
    async (route) => {
      if (route.request().method() !== 'GET') return route.continue();
      await route.fulfill({
        json: {
          items: [
            {
              id: 'run-paused',
              session_id: sessionId,
              plan_revision_id: revisionId,
              sequence_number: 1,
              operation: 'generate',
              label: 'Paused run A',
              status: 'paused',
              progress: 40,
              created_at: new Date().toISOString(),
              updated_at: new Date().toISOString()
            }
          ]
        }
      });
    }
  );
  await page.goto(`/sessions/${sessionId}`);
  // Cold Windows CI loads can still be fetching route chunks after navigation.
  // Give bootstrap its own budget before asserting the paused-run controls.
  await expect(page.locator('.app-shell')).toBeVisible({ timeout: 30_000 });
  const resume = page
    .locator('.generation-drawer')
    .getByRole('button', { name: 'Resume previous run' });
  await expect(resume).toBeVisible();
  await expect(resume).toHaveAttribute(
    'title',
    'Continue the paused run with its saved voice and settings'
  );
  const dialog = await openDialog(page);
  const note = dialog.getByTestId('generation-start-resume-note');
  await expect(note).toContainText('Resume paused run is separate');
  await expect(note).toContainText('Paused run A');
  await expect(note).toContainText('saved voice and settings');
  await expect(note).toContainText('may be regenerated');
});

test('failed generation offers the safe continuation action', async ({
  page
}) => {
  const { sessionId, revisionId } = await setupSession(page);
  await mockPreview(page, sessionId, () => previewsFor(revisionId).missing);
  let startCount = 0;
  await page.route(
    `**/api/v1/sessions/${sessionId}/generation-runs`,
    async (route) => {
      if (route.request().method() === 'POST') {
        startCount += 1;
        return route.fulfill({
          status: 409,
          json: { error: { message: 'Unexpected start' } }
        });
      }
      return route.fulfill({
        json: {
          items: [
            {
              ...startedRun(sessionId, revisionId),
              id: 'failed-original-run',
              status: 'failed',
              error_message: 'A block needs correction.'
            }
          ]
        }
      });
    }
  );
  await page.goto(`/sessions/${sessionId}`);
  await page.getByRole('button', { name: 'Generation', exact: true }).click();
  const recovery = page.getByTestId('generation-recovery-continue');
  await expect(recovery).toBeVisible();
  await recovery.click();
  const dialog = page.getByTestId('generation-start-dialog');
  await expect(dialog).toBeVisible();
  await expect(
    dialog.getByTestId('generation-start-mode-continue')
  ).toBeChecked();
  await expect(dialog.getByTestId('generation-start-counts')).toContainText(
    '4 kept'
  );
  expect(startCount).toBe(0);
});

test('an incomplete preview cannot bypass the confirmation guard', async ({
  page
}) => {
  const { sessionId, revisionId } = await setupSession(page);
  await mockPreview(page, sessionId, () => ({
    ...previewsFor(revisionId).missing,
    selection_hash: null
  }));
  const started = await mockStart(page, sessionId, () => ({
    status: 202,
    json: startedRun(sessionId, revisionId)
  }));
  await page.goto(`/sessions/${sessionId}`);
  const dialog = await openDialog(page);
  await expect(dialog.getByTestId('generation-start-error')).toContainText(
    'preview was incomplete'
  );
  await expect(dialog.getByTestId('generation-start-submit')).toBeDisabled();
  expect(started).toHaveLength(0);
});

test('regenerate everything requires deliberate acknowledgment', async ({
  page
}) => {
  const { sessionId, revisionId } = await setupSession(page);
  const canned = previewsFor(revisionId);
  await mockPreview(page, sessionId, (body) =>
    body.missing_only ? canned.missing : { ...canned.all, missing_count: 0 }
  );
  const started = await mockStart(page, sessionId, () => ({
    status: 202,
    json: startedRun(sessionId, revisionId)
  }));
  await page.goto(`/sessions/${sessionId}`);
  const dialog = await openDialog(page);
  await dialog.getByTestId('generation-start-mode-all').check();
  const submit = dialog.getByTestId('generation-start-submit');
  await expect(submit).toHaveText('Generate 5 blocks');
  await expect(submit).toBeDisabled();
  await expect(dialog.getByTestId('generation-start-reasons')).toContainText(
    'Regenerated by explicit choice: 5'
  );
  expect(started).toHaveLength(0);
  await dialog.getByTestId('generation-start-ack').check();
  await submit.click();
  await expect(dialog).toBeHidden();
  expect(started).toHaveLength(1);
  expect(started[0]).toMatchObject({
    missing_only: false,
    stale_only: false,
    expected_selection_hash: 'hash-all'
  });
});
