<script lang="ts">
  import { File, FileAudio, FileText, Link2, Plus, Search } from '@lucide/svelte';
  import { api, uploadManagedFile } from '$lib/api';
  let sources=$state<any[]>([]);let search=$state('');let uploading=$state(false);let progress=$state(0);let error=$state('');
  const visible=$derived(sources.filter((item)=>item.display_name.toLowerCase().includes(search.toLowerCase())||item.kind.includes(search.toLowerCase())));
  async function load(){sources=(await api<{items:any[]}>('/sources')).items}load();
  async function upload(event:Event){const input=event.currentTarget as HTMLInputElement;const file=input.files?.[0];if(!file)return;uploading=true;try{await uploadManagedFile(file,undefined,(value)=>progress=value);await load()}catch(caught){error=caught instanceof Error?caught.message:String(caught)}finally{uploading=false;input.value=''}}
</script>
<div class="mx-auto max-w-7xl"><header class="flex flex-wrap items-end justify-between gap-5"><div><div class="eyebrow">Source library</div><h1 class="mt-2 text-4xl font-semibold">Reusable material</h1><p class="muted mt-3">A source can be attached to several sessions while retaining one managed identity.</p></div><label class="flex cursor-pointer items-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-3 text-sm font-semibold text-white"><Plus size={17}/>{uploading?`Uploading ${Math.round(progress*100)}%`:'Add source'}<input type="file" class="sr-only" onchange={upload}/></label></header>{#if error}<p class="mt-4 text-sm text-red-500">{error}</p>{/if}<div class="mt-7 flex items-center gap-3 rounded-xl border border-[var(--line)] bg-[var(--paper-strong)] px-4"><Search class="muted" size={17}/><input bind:value={search} placeholder="Search by name or file type" class="w-full bg-transparent py-3 outline-none"/></div><div class="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{#each visible as item}<article class="surface rounded-2xl p-5"><div class="flex items-start gap-3"><div class="grid size-10 place-items-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]">{#if item.kind.match(/wav|mp3|flac|m4a/)}<FileAudio size={18}/>{:else if item.external_path}<Link2 size={18}/>{:else}<FileText size={18}/>{/if}</div><div class="min-w-0"><h2 class="truncate font-semibold">{item.display_name}</h2><div class="muted mt-1 text-xs uppercase">{item.kind} · {item.state}</div></div></div><dl class="muted mt-5 grid grid-cols-2 gap-3 text-xs"><div><dt>Size</dt><dd class="mt-1 font-semibold text-[var(--ink)]">{item.size_bytes?`${(item.size_bytes/1048576).toFixed(1)} MB`:'External'}</dd></div><div><dt>Versions</dt><dd class="mt-1 font-semibold text-[var(--ink)]">Revision {item.revision}</dd></div></dl>{#if item.artifact_id}<a href={`/api/v1/artifacts/${item.artifact_id}/content`} target="_blank" class="mt-4 block rounded-xl border border-[var(--line)] px-3 py-2 text-center text-xs font-semibold">Preview source</a>{/if}</article>{:else}<div class="muted col-span-full rounded-2xl border border-dashed border-[var(--line)] p-12 text-center"><File class="mx-auto mb-3" size={24}/>No reusable sources yet.</div>{/each}</div></div>
