<script lang="ts">
  import { FileAudio, FileText, FileUp, History, Link2, Plus, Trash2 } from '@lucide/svelte';
  import { page } from '$app/state';
  import { api,uploadManagedFile } from '$lib/api';
  import PdfEditor from '$lib/PdfEditor.svelte';
  import ArtifactPreview from '$lib/ArtifactPreview.svelte';
  let sources=$state<any[]>([]); let library=$state<any[]>([]); let reusableId=$state(''); let uploading=$state(false); let progress=$state(0); let error=$state(''); let message=$state(''); let pdf=$state<any>(null); let preview=$state<any|null>(null); const sessionId=String(page.params.id);
  async function load(){const [attached,reusable]=await Promise.all([api<{items:any[]}>(`/sessions/${sessionId}/sources`),api<{items:any[]}>('/sources')]);sources=attached.items;library=reusable.items.filter((item)=>!sources.some((source)=>source.id===item.id));reusableId=library.some((item)=>item.id===reusableId)?reusableId:library[0]?.id??''}
  async function upload(event:Event){const input=event.currentTarget as HTMLInputElement;const file=input.files?.[0];if(!file)return;uploading=true;error='';try{await uploadManagedFile(file,sessionId,(value)=>progress=value);message='Source uploaded and selected as current.';await load()}catch(caught){error=caught instanceof Error?caught.message:String(caught)}finally{uploading=false;input.value=''}}
  async function makeCurrent(source:any){error='';try{await api(`/sessions/${sessionId}/sources`,{method:'POST',body:JSON.stringify({source_asset_id:source.id,role:source.attachment.role})});message=`${source.display_name} is now the current ${source.attachment.role} source.`;await load()}catch(caught){error=caught instanceof Error?caught.message:String(caught)}}
  async function attachReusable(){if(!reusableId)return;error='';try{await api(`/sessions/${sessionId}/sources`,{method:'POST',body:JSON.stringify({source_asset_id:reusableId,role:'primary'})});message='Reusable source attached and selected.';await load()}catch(caught){error=caught instanceof Error?caught.message:String(caught)}}
  async function detach(source:any){if(!confirm(`Detach ${source.display_name} from this session? The library source and managed file will be preserved.`))return;error='';try{await api(`/sessions/${sessionId}/sources/${source.attachment.id}`,{method:'DELETE',headers:{'If-Match':`"${source.attachment.revision}"`}});message='Source detached. Its library record and file were preserved.';await load()}catch(caught){error=caught instanceof Error?caught.message:String(caught)}}
  load().catch((caught)=>error=caught instanceof Error?caught.message:String(caught));
</script>

<div>
  <div class="flex flex-wrap items-end justify-between gap-4"><div><h2 class="text-2xl font-semibold">Sources and versions</h2><p class="muted mt-2">Every attachment remains inspectable. Selecting an earlier source changes the current input without overwriting or deleting later files.</p></div><label class="flex cursor-pointer items-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-2.5 text-sm font-semibold text-white"><FileUp size={16}/>{uploading?`${Math.round(progress*100)}%`:'Upload new version'}<input type="file" class="sr-only" onchange={upload}/></label></div>
  {#if error}<p class="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-500">{error}</p>{/if}{#if message}<p class="mt-4 rounded-xl bg-[var(--accent-soft)] p-3 text-sm">{message}</p>{/if}
  <section class="surface mt-5 flex flex-wrap items-end gap-3 rounded-2xl p-4"><label class="min-w-64 flex-1 text-xs font-semibold">Attach from Source Library<select bind:value={reusableId} class="field"><option value="">No unattached sources available</option>{#each library as item}<option value={item.id}>{item.display_name} · {item.kind}</option>{/each}</select></label><button onclick={attachReusable} disabled={!reusableId} class="action primary"><Link2 size={15}/> Attach and select</button></section>
  <div class="mt-6 grid gap-4 md:grid-cols-2">
    {#each sources as source}
      <article class:stale={!source.attachment.is_current} class="surface rounded-2xl p-5"><div class="flex items-start gap-3"><div class="grid size-10 place-items-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]">{#if source.kind.match(/mp3|wav|flac|mp4|mkv/)}<FileAudio size={18}/>{:else}<FileText size={18}/>{/if}</div><div class="min-w-0 flex-1"><h3 class="truncate font-semibold">{source.display_name}</h3><div class="muted mt-1 text-xs uppercase">{source.kind} · {source.attachment.role}</div><div class="mt-2 flex flex-wrap gap-2 text-[.68rem] font-semibold"><span class:current={source.attachment.is_current} class="badge">{source.attachment.is_current?'Current input':'Previous version'}</span><span class="badge">Record revision {source.revision}</span><span class="badge">{source.reference_count} session reference{source.reference_count===1?'':'s'}</span></div></div><History size={16}/></div><div class="mt-4 flex flex-wrap gap-2">{#if source.artifact_id}<button onclick={()=>{preview={...source,id:source.artifact_id,role:'source',relative_path:source.display_name}}} class="action">Preview</button>{/if}{#if !source.attachment.is_current}<button onclick={()=>makeCurrent(source)} class="action primary">Make current</button>{/if}{#if source.kind==='pdf'}<button onclick={()=>{pdf={id:source.artifact_id,filename:source.display_name}}} class="action">Preprocess PDF</button>{/if}<button onclick={()=>detach(source)} class="action danger"><Trash2 size={14}/> Detach</button></div></article>
    {:else}<div class="muted col-span-full rounded-2xl border border-dashed border-[var(--line)] p-10 text-center"><Plus class="mx-auto mb-2"/>Add the first source for this session.</div>{/each}
  </div>
</div>
{#if pdf}<PdfEditor sessionId={sessionId} source={pdf} onclose={()=>pdf=null}/>{/if}
{#if preview}<ArtifactPreview artifact={preview} onclose={()=>preview=null}/>{/if}
<style>.stale{opacity:.7}.action{display:flex;align-items:center;gap:.35rem;border:1px solid var(--line);border-radius:.65rem;padding:.5rem .7rem;font-size:.72rem;font-weight:650}.action.primary{background:var(--accent);color:white}.action.danger{color:#dc4b4b}.action:disabled{opacity:.4}.field{margin-top:.35rem;width:100%;border:1px solid var(--line);border-radius:.65rem;background:var(--paper);padding:.55rem}.badge{border-radius:999px;background:var(--paper);padding:.25rem .5rem;color:var(--muted)}.badge.current{background:var(--accent-soft);color:var(--accent)}</style>
