"""Public MCP input schemas."""

from .common import ToolEnvelope, ToolInput, WorkReference
from .dispatch import (
    ClaimDispatchBatchInput,
    CreateDispatchRunInput,
    DispatchCorrectionOperationInput,
    DispatchCorrectionResultInput,
    DispatchStructuredResultInput,
    DispatchTranslationItemInput,
    DispatchTranslationResultInput,
    GetDispatchRunInput,
    ListDispatchRunsInput,
    ReleaseDispatchBatchInput,
    RenewDispatchBatchInput,
    SubmitDispatchBatchInput,
)
from .guidance import GUIDE_TOPICS, ExplainSystemInput, GuideTopic
from .inventory import ListArtifactsInput, ProviderStatusInput, VoiceCatalogInput
from .manager import (
    ControlRuntimeInput,
    ExecuteComponentPlanInput,
    ManagerDesiredComponentInput,
    PlanComponentChangeInput,
)
from .recommendations import RecommendNextStepsInput
from .sessions import (
    AttachExistingSourceInput,
    CreateSessionInput,
    GetSessionInput,
    GetSessionSettingsInput,
    GetWorkflowInput,
    ListSessionsInput,
    ListSourcesInput,
    UpdateSessionInput,
    UpdateSessionSettingsInput,
)
from .source_cleaning_dispatch import (
    ClaimSourceCleaningDispatchBatchInput,
    CreateSourceCleaningDispatchRunInput,
    GetSourceCleaningDispatchRunInput,
    InspectSourceCleaningDispatchExtractionInput,
    ListSourceCleaningDispatchRunsInput,
    ReleaseSourceCleaningDispatchBatchInput,
    RenewSourceCleaningDispatchBatchInput,
    SourceCleaningDispatchDecisionInput,
    SourceCleaningDispatchOperationInput,
    SourceCleaningDispatchResultInput,
    SubmitSourceCleaningDispatchBatchInput,
)
from .system import CapabilitiesInput, SystemStatusInput, TargetStatusInput
from .work import (
    CancelWorkInput,
    GetWorkInput,
    GetWorkLogInput,
    ListWorkInput,
)
from .workflow import (
    ExecuteWorkflowPlanInput,
    PlanWorkflowInput,
    RunWorkflowInput,
)

TOOL_INPUT_MODELS = (
    ExplainSystemInput,
    RecommendNextStepsInput,
    TargetStatusInput,
    SystemStatusInput,
    CapabilitiesInput,
    ListSessionsInput,
    GetSessionInput,
    GetDispatchRunInput,
    GetSourceCleaningDispatchRunInput,
    GetWorkflowInput,
    GetSessionSettingsInput,
    ListSourcesInput,
    ListArtifactsInput,
    ListDispatchRunsInput,
    ListSourceCleaningDispatchRunsInput,
    ProviderStatusInput,
    VoiceCatalogInput,
    ListWorkInput,
    GetWorkInput,
    GetWorkLogInput,
    CreateSessionInput,
    CreateDispatchRunInput,
    CreateSourceCleaningDispatchRunInput,
    UpdateSessionInput,
    AttachExistingSourceInput,
    UpdateSessionSettingsInput,
    PlanWorkflowInput,
    ExecuteWorkflowPlanInput,
    CancelWorkInput,
    ManagerDesiredComponentInput,
    PlanComponentChangeInput,
    ExecuteComponentPlanInput,
    ControlRuntimeInput,
    ClaimDispatchBatchInput,
    ReleaseDispatchBatchInput,
    RenewDispatchBatchInput,
    SubmitDispatchBatchInput,
    ClaimSourceCleaningDispatchBatchInput,
    InspectSourceCleaningDispatchExtractionInput,
    ReleaseSourceCleaningDispatchBatchInput,
    RenewSourceCleaningDispatchBatchInput,
    SubmitSourceCleaningDispatchBatchInput,
)

__all__ = [
    "AttachExistingSourceInput",
    "CancelWorkInput",
    "ClaimDispatchBatchInput",
    "ClaimSourceCleaningDispatchBatchInput",
    "CapabilitiesInput",
    "CreateSessionInput",
    "CreateDispatchRunInput",
    "CreateSourceCleaningDispatchRunInput",
    "DispatchCorrectionOperationInput",
    "DispatchCorrectionResultInput",
    "DispatchStructuredResultInput",
    "DispatchTranslationItemInput",
    "DispatchTranslationResultInput",
    "ExplainSystemInput",
    "GUIDE_TOPICS",
    "GuideTopic",
    "ExecuteWorkflowPlanInput",
    "GetSessionInput",
    "GetDispatchRunInput",
    "GetSourceCleaningDispatchRunInput",
    "InspectSourceCleaningDispatchExtractionInput",
    "GetSessionSettingsInput",
    "GetWorkInput",
    "GetWorkLogInput",
    "GetWorkflowInput",
    "ListArtifactsInput",
    "ListDispatchRunsInput",
    "ListSourceCleaningDispatchRunsInput",
    "ListSessionsInput",
    "ListSourcesInput",
    "ListWorkInput",
    "ControlRuntimeInput",
    "ExecuteComponentPlanInput",
    "ManagerDesiredComponentInput",
    "PlanComponentChangeInput",
    "ProviderStatusInput",
    "PlanWorkflowInput",
    "RecommendNextStepsInput",
    "ReleaseDispatchBatchInput",
    "ReleaseSourceCleaningDispatchBatchInput",
    "RenewDispatchBatchInput",
    "RenewSourceCleaningDispatchBatchInput",
    "RunWorkflowInput",
    "SystemStatusInput",
    "SubmitDispatchBatchInput",
    "SourceCleaningDispatchDecisionInput",
    "SourceCleaningDispatchOperationInput",
    "SourceCleaningDispatchResultInput",
    "SubmitSourceCleaningDispatchBatchInput",
    "TargetStatusInput",
    "TOOL_INPUT_MODELS",
    "ToolEnvelope",
    "ToolInput",
    "UpdateSessionInput",
    "UpdateSessionSettingsInput",
    "WorkReference",
    "VoiceCatalogInput",
]
