"""Generate pip compatibility manifests from the authoritative project metadata."""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GENERATED_HEADER = (
    "# Generated by scripts/generate_requirements.py from {source}.\n"
    "# Do not edit this file directly; update the source pyproject.toml.\n"
)
PACKAGE_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*")


def _normalized_name(requirement: str) -> str:
    match = PACKAGE_NAME.match(requirement.strip())
    if match is None:
        raise ValueError(f"Unsupported dependency declaration: {requirement!r}")
    return re.sub(r"[-_.]+", "-", match.group(0)).lower()


def _dependencies(source: Path, extras: tuple[str, ...]) -> list[str]:
    document = tomllib.loads(source.read_text(encoding="utf-8"))
    project = document.get("project", {})
    dependencies = list(project.get("dependencies", []))
    optional = project.get("optional-dependencies", {})
    for extra in extras:
        if extra not in optional:
            raise KeyError(f"Unknown optional dependency group {extra!r} in {source}")
        dependencies.extend(optional[extra])

    result: list[str] = []
    seen: dict[str, str] = {}
    for dependency in dependencies:
        normalized = _normalized_name(dependency)
        previous = seen.get(normalized)
        if previous is not None:
            if previous != dependency:
                raise ValueError(
                    f"Conflicting declarations for {normalized!r}: "
                    f"{previous!r} and {dependency!r}"
                )
            continue
        seen[normalized] = dependency
        result.append(dependency)
    return result


def _render(source: Path, extras: tuple[str, ...]) -> str:
    relative_source = source.relative_to(ROOT).as_posix()
    dependencies = _dependencies(source, extras)
    return (
        GENERATED_HEADER.format(source=relative_source)
        + "\n".join(dependencies)
        + "\n"
    )


TARGETS = (
    (
        ROOT / "requirements.txt",
        ROOT / "pyproject.toml",
        ("ocr", "text-normalization", "credential-stores"),
    ),
    (
        ROOT / "requirements-installer.txt",
        ROOT / "pandrator_installer" / "pyproject.toml",
        ("gui", "build"),
    ),
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if a generated manifest differs instead of rewriting it.",
    )
    arguments = parser.parse_args(argv)

    stale: list[Path] = []
    for destination, source, extras in TARGETS:
        expected = _render(source, extras)
        if arguments.check:
            if not destination.exists() or destination.read_text(encoding="utf-8") != expected:
                stale.append(destination)
            continue
        destination.write_text(expected, encoding="utf-8", newline="\n")
        print(destination.relative_to(ROOT))

    if stale:
        for destination in stale:
            print(
                f"{destination.relative_to(ROOT)} is stale; "
                "run python scripts/generate_requirements.py",
                file=sys.stderr,
            )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
