"""Declarative MCP action catalog, independent of handlers and transport."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class RiskClass(StrEnum):
    READ = "read"
    WRITE = "write"
    RUN = "run"
    CANCEL = "cancel"
    MANAGER_RUNTIME = "manager_runtime"
    MANAGER_MUTATE = "manager_mutate"


@dataclass(frozen=True, slots=True)
class ActionSpec:
    name: str
    title: str
    input_model: str
    risk: RiskClass
    required_scope: str | None
    downstream_operation_id: str | None
    method: str | None
    path: str | None
    enabled: bool
    requires_idempotency: bool = False
    requires_confirmation: bool = False

    @property
    def mutating(self) -> bool:
        return self.risk != RiskClass.READ


class ActionCatalog:
    def __init__(self, actions: tuple[ActionSpec, ...]):
        self._actions = {action.name: action for action in actions}
        if len(self._actions) != len(actions):
            raise ValueError("Action names must be unique.")

    def get(self, name: str) -> ActionSpec:
        return self._actions[name]

    def list(self) -> tuple[ActionSpec, ...]:
        return tuple(self._actions[name] for name in sorted(self._actions))


ACTION_CATALOG = ActionCatalog(
    (
        ActionSpec(
            "pandrator_explain_system",
            "Explain Pandrator",
            "ExplainSystemInput",
            RiskClass.READ,
            None,
            None,
            None,
            None,
            True,
        ),
        ActionSpec(
            "pandrator_recommend_next_steps",
            "Recommend safe next steps",
            "RecommendNextStepsInput",
            RiskClass.READ,
            "app.read",
            None,
            None,
            None,
            True,
        ),
        ActionSpec(
            "pandrator_get_target_status",
            "Inspect configured target status",
            "TargetStatusInput",
            RiskClass.READ,
            None,
            "getHealth",
            "GET",
            "/api/v1/health",
            True,
        ),
        ActionSpec(
            "pandrator_get_system_status",
            "Inspect Pandrator status",
            "SystemStatusInput",
            RiskClass.READ,
            "app.read",
            "getHealth",
            "GET",
            "/api/v1/health",
            True,
        ),
        ActionSpec(
            "pandrator_get_capabilities",
            "Inspect Pandrator capabilities",
            "CapabilitiesInput",
            RiskClass.READ,
            "app.read",
            "getCapabilities",
            "GET",
            "/api/v1/capabilities",
            True,
        ),
        ActionSpec(
            "pandrator_list_sessions",
            "List Pandrator sessions",
            "ListSessionsInput",
            RiskClass.READ,
            "app.read",
            "listSessions",
            "GET",
            "/api/v1/sessions",
            True,
        ),
        ActionSpec(
            "pandrator_get_session",
            "Inspect a Pandrator session",
            "GetSessionInput",
            RiskClass.READ,
            "app.read",
            "getSession",
            "GET",
            "/api/v1/sessions/{sessionId}",
            True,
        ),
        ActionSpec(
            "pandrator_get_workflow",
            "Inspect a session workflow",
            "GetWorkflowInput",
            RiskClass.READ,
            "app.read",
            "getWorkflow",
            "GET",
            "/api/v1/sessions/{sessionId}/workflow",
            True,
        ),
        ActionSpec(
            "pandrator_preview_subtitles",
            "Preview subtitle cues, transcript segments, and translations",
            "PreviewSubtitlesInput",
            RiskClass.READ,
            "app.read",
            "getSubtitleDocuments",
            "GET",
            "/api/v1/sessions/{sessionId}/subtitles",
            True,
        ),
        ActionSpec(
            "pandrator_replace_subtitle_text",
            "Find and replace text across subtitle cues with revision guard",
            "ReplaceSubtitleTextInput",
            RiskClass.WRITE,
            "app.write",
            "saveSubtitleReview",
            "POST",
            "/api/v1/sessions/{sessionId}/subtitles/{stage}/review",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_patch_subtitle_cues",
            "Patch specific subtitle cues by ordinal with revision guard",
            "PatchSubtitleCuesInput",
            RiskClass.WRITE,
            "app.write",
            "saveSubtitleReview",
            "POST",
            "/api/v1/sessions/{sessionId}/subtitles/{stage}/review",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_import_subtitles",
            "Import reviewed subtitles from raw SRT text or file",
            "ImportSubtitlesInput",
            RiskClass.WRITE,
            "app.write",
            "saveSubtitleReview",
            "POST",
            "/api/v1/sessions/{sessionId}/subtitles/{stage}/review",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_get_session_settings",
            "Inspect effective session settings",
            "GetSessionSettingsInput",
            RiskClass.READ,
            "app.read",
            "getSessionSettings",
            "GET",
            "/api/v1/sessions/{sessionId}/settings/{section}",
            True,
        ),
        ActionSpec(
            "pandrator_list_sources",
            "List reusable source assets",
            "ListSourcesInput",
            RiskClass.READ,
            "app.read",
            "listSourceAssets",
            "GET",
            "/api/v1/sources",
            True,
        ),
        ActionSpec(
            "pandrator_browse_local_sources",
            "Browse approved local source roots",
            "BrowseLocalSourcesInput",
            RiskClass.READ,
            None,
            None,
            None,
            None,
            True,
        ),
        ActionSpec(
            "pandrator_import_local_source",
            "Import and attach a local source",
            "ImportLocalSourceInput",
            RiskClass.WRITE,
            "app.write",
            "initializeChunkUpload",
            "POST",
            "/api/v1/uploads/init",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_list_artifacts",
            "List artifact metadata",
            "ListArtifactsInput",
            RiskClass.READ,
            "app.read",
            "listArtifacts",
            "GET",
            "/api/v1/artifacts",
            True,
        ),
        ActionSpec(
            "pandrator_get_provider_status",
            "Inspect provider readiness",
            "ProviderStatusInput",
            RiskClass.READ,
            "app.read",
            "listProviders",
            "GET",
            "/api/v1/providers",
            True,
        ),
        ActionSpec(
            "pandrator_get_tts_catalog",
            "Inspect TTS services, models, and voices",
            "TtsCatalogInput",
            RiskClass.READ,
            "app.read",
            "listTtsServices",
            "GET",
            "/api/v1/services/tts",
            True,
        ),
        ActionSpec(
            "pandrator_configure_tts",
            "Configure a catalog-backed TTS selection",
            "ConfigureTtsInput",
            RiskClass.WRITE,
            "app.write",
            "putSessionSettings",
            "PUT",
            "/api/v1/sessions/{sessionId}/settings/tts",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_get_voice_catalog",
            "Inspect the voice catalog",
            "VoiceCatalogInput",
            RiskClass.READ,
            "app.read",
            "listVoices",
            "GET",
            "/api/v1/voices",
            True,
        ),
        ActionSpec(
            "pandrator_list_work",
            "List durable work",
            "ListWorkInput",
            RiskClass.READ,
            "app.read",
            "listWork",
            "GET",
            "/api/v1/work",
            True,
        ),
        ActionSpec(
            "pandrator_list_generation_runs",
            "List reviewable generation runs",
            "ListGenerationRunsInput",
            RiskClass.READ,
            "app.read",
            "listGenerationRuns",
            "GET",
            "/api/v1/sessions/{sessionId}/generation-runs",
            True,
        ),
        ActionSpec(
            "pandrator_list_generation_segments",
            "List generation segments and audio takes",
            "ListGenerationSegmentsInput",
            RiskClass.READ,
            "app.read",
            "listGenerationSegments",
            "GET",
            "/api/v1/sessions/{sessionId}/generation-segments",
            True,
        ),
        ActionSpec(
            "pandrator_update_generation_segment",
            "Update generation segment text or voice overrides",
            "UpdateGenerationSegmentInput",
            RiskClass.WRITE,
            "app.write",
            "updateGenerationSegment",
            "PATCH",
            "/api/v1/generation-segments/{segmentId}",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_select_take",
            "Select an alternative audio take for a generation segment",
            "SelectTakeInput",
            RiskClass.WRITE,
            "app.write",
            "selectGenerationTake",
            "POST",
            "/api/v1/generation-segments/{segmentId}/takes/{takeId}/select",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_regenerate_segments",
            "Trigger targeted synthesis for specific generation segments",
            "RegenerateSegmentsInput",
            RiskClass.RUN,
            "app.run",
            "startGenerationRun",
            "POST",
            "/api/v1/sessions/{sessionId}/generation-runs",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_assemble_generation_run",
            "Queue output mix assembly for a generation run",
            "AssembleGenerationRunInput",
            RiskClass.RUN,
            "app.run",
            "createOutputAssembly",
            "POST",
            "/api/v1/sessions/{sessionId}/output-assemblies",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_get_work",
            "Inspect durable work",
            "GetWorkInput",
            RiskClass.READ,
            "app.read",
            "getWork",
            "GET",
            "/api/v1/work/{jobId}",
            True,
        ),
        ActionSpec(
            "pandrator_get_work_log",
            "Inspect a redacted work log",
            "GetWorkLogInput",
            RiskClass.READ,
            "app.read",
            "listWorkEvents",
            "GET",
            "/api/v1/work/{jobId}/events",
            True,
        ),
        ActionSpec(
            "pandrator_manager_status",
            "Inspect Pandrator Manager status",
            "SystemStatusInput",
            RiskClass.READ,
            "manager.read",
            "getManagerStatus",
            "GET",
            "/api/v1/manager/status",
            True,
        ),
        ActionSpec(
            "pandrator_manager_doctor",
            "Inspect Pandrator Manager diagnostics",
            "SystemStatusInput",
            RiskClass.READ,
            "manager.read",
            "getManagerDoctorReport",
            "GET",
            "/api/v1/manager/doctor",
            True,
        ),
        ActionSpec(
            "pandrator_list_dispatch_runs",
            "List subtitle dispatch runs",
            "ListDispatchRunsInput",
            RiskClass.READ,
            "app.read",
            "listDispatchRuns",
            "GET",
            "/api/v1/sessions/{sessionId}/dispatch-runs",
            True,
        ),
        ActionSpec(
            "pandrator_get_dispatch_run",
            "Inspect a subtitle dispatch run",
            "GetDispatchRunInput",
            RiskClass.READ,
            "app.read",
            "getDispatchRun",
            "GET",
            "/api/v1/dispatch-runs/{runId}",
            True,
        ),
        ActionSpec(
            "pandrator_create_dispatch_run",
            "Create a subtitle dispatch run",
            "CreateDispatchRunInput",
            RiskClass.RUN,
            "app.run",
            "createDispatchRun",
            "POST",
            "/api/v1/sessions/{sessionId}/dispatch-runs",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_claim_dispatch_batch",
            "Claim a subtitle dispatch batch",
            "ClaimDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "claimDispatchBatch",
            "POST",
            "/api/v1/dispatch-runs/{runId}/claim",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_renew_dispatch_batch",
            "Renew a subtitle dispatch lease",
            "RenewDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "renewDispatchBatch",
            "POST",
            "/api/v1/dispatch-batches/{batchId}/renew",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_release_dispatch_batch",
            "Release a subtitle dispatch lease",
            "ReleaseDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "releaseDispatchBatch",
            "POST",
            "/api/v1/dispatch-batches/{batchId}/release",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_submit_dispatch_batch",
            "Submit a subtitle dispatch batch",
            "SubmitDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "submitDispatchBatch",
            "POST",
            "/api/v1/dispatch-batches/{batchId}/submit",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_list_source_cleaning_dispatch_runs",
            "List passive PDF/EPUB cleanup runs",
            "ListSourceCleaningDispatchRunsInput",
            RiskClass.READ,
            "app.read",
            "listSourceCleaningDispatchRuns",
            "GET",
            "/api/v1/sessions/{sessionId}/source-cleaning-dispatch-runs",
            True,
        ),
        ActionSpec(
            "pandrator_get_source_cleaning_dispatch_run",
            "Inspect a passive PDF/EPUB cleanup run",
            "GetSourceCleaningDispatchRunInput",
            RiskClass.READ,
            "app.read",
            "getSourceCleaningDispatchRun",
            "GET",
            "/api/v1/source-cleaning-dispatch-runs/{runId}",
            True,
        ),
        ActionSpec(
            "pandrator_create_source_cleaning_dispatch_run",
            "Create a passive PDF/EPUB cleanup run",
            "CreateSourceCleaningDispatchRunInput",
            RiskClass.RUN,
            "app.run",
            "createSourceCleaningDispatchRun",
            "POST",
            "/api/v1/sessions/{sessionId}/source-cleaning-dispatch-runs",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_claim_source_cleaning_dispatch_batch",
            "Claim a PDF/EPUB cleanup phase",
            "ClaimSourceCleaningDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "claimSourceCleaningDispatchBatch",
            "POST",
            "/api/v1/source-cleaning-dispatch-runs/{runId}/claim",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_renew_source_cleaning_dispatch_batch",
            "Renew a PDF/EPUB cleanup lease",
            "RenewSourceCleaningDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "renewSourceCleaningDispatchBatch",
            "POST",
            "/api/v1/source-cleaning-dispatch-batches/{batchId}/renew",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_release_source_cleaning_dispatch_batch",
            "Release a PDF/EPUB cleanup lease",
            "ReleaseSourceCleaningDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "releaseSourceCleaningDispatchBatch",
            "POST",
            "/api/v1/source-cleaning-dispatch-batches/{batchId}/release",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_inspect_source_cleaning_dispatch_extraction",
            "Inspect a leased PDF/EPUB extraction",
            "InspectSourceCleaningDispatchExtractionInput",
            RiskClass.RUN,
            "app.run",
            "inspectSourceCleaningDispatchExtraction",
            "POST",
            "/api/v1/source-cleaning-dispatch-batches/{batchId}/inspect",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_submit_source_cleaning_dispatch_batch",
            "Submit a PDF/EPUB cleanup phase",
            "SubmitSourceCleaningDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "submitSourceCleaningDispatchBatch",
            "POST",
            "/api/v1/source-cleaning-dispatch-batches/{batchId}/submit",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_list_speech_optimization_dispatch_runs",
            "List passive speech-optimization runs",
            "ListSpeechOptimizationDispatchRunsInput",
            RiskClass.READ,
            "app.read",
            "listSpeechOptimizationDispatchRuns",
            "GET",
            "/api/v1/sessions/{sessionId}/speech-optimization-dispatch-runs",
            True,
        ),
        ActionSpec(
            "pandrator_get_speech_optimization_dispatch_run",
            "Inspect a passive speech-optimization run",
            "GetSpeechOptimizationDispatchRunInput",
            RiskClass.READ,
            "app.read",
            "getSpeechOptimizationDispatchRun",
            "GET",
            "/api/v1/speech-optimization-dispatch-runs/{runId}",
            True,
        ),
        ActionSpec(
            "pandrator_create_speech_optimization_dispatch_run",
            "Create a passive speech-optimization run",
            "CreateSpeechOptimizationDispatchRunInput",
            RiskClass.RUN,
            "app.run",
            "createSpeechOptimizationDispatchRun",
            "POST",
            "/api/v1/sessions/{sessionId}/speech-optimization-dispatch-runs",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_claim_speech_optimization_dispatch_batch",
            "Claim a passive speech-text batch",
            "ClaimSpeechOptimizationDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "claimSpeechOptimizationDispatchBatch",
            "POST",
            "/api/v1/speech-optimization-dispatch-runs/{runId}/claim",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_renew_speech_optimization_dispatch_batch",
            "Renew a speech-optimization lease",
            "RenewSpeechOptimizationDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "renewSpeechOptimizationDispatchBatch",
            "POST",
            "/api/v1/speech-optimization-dispatch-batches/{batchId}/renew",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_release_speech_optimization_dispatch_batch",
            "Release a speech-optimization lease",
            "ReleaseSpeechOptimizationDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "releaseSpeechOptimizationDispatchBatch",
            "POST",
            "/api/v1/speech-optimization-dispatch-batches/{batchId}/release",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_submit_speech_optimization_dispatch_batch",
            "Submit a passive speech-text batch",
            "SubmitSpeechOptimizationDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "submitSpeechOptimizationDispatchBatch",
            "POST",
            "/api/v1/speech-optimization-dispatch-batches/{batchId}/submit",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_create_session",
            "Create a Pandrator session",
            "CreateSessionInput",
            RiskClass.WRITE,
            "app.write",
            "createSession",
            "POST",
            "/api/v1/sessions",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_update_session",
            "Update a Pandrator session",
            "UpdateSessionInput",
            RiskClass.WRITE,
            "app.write",
            "updateSession",
            "PATCH",
            "/api/v1/sessions/{sessionId}",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_attach_existing_source",
            "Attach a reusable source asset",
            "AttachExistingSourceInput",
            RiskClass.WRITE,
            "app.write",
            "attachSessionSource",
            "POST",
            "/api/v1/sessions/{sessionId}/sources",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_update_session_settings",
            "Update one session settings section",
            "UpdateSessionSettingsInput",
            RiskClass.WRITE,
            "app.write",
            "putSessionSettings",
            "PUT",
            "/api/v1/sessions/{sessionId}/settings/{section}",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_plan_workflow",
            "Preview an exact workflow execution plan",
            "PlanWorkflowInput",
            RiskClass.READ,
            "app.read",
            "createWorkflowPlan",
            "POST",
            "/api/v1/sessions/{sessionId}/workflow-plans",
            True,
        ),
        ActionSpec(
            "pandrator_plan_export_variant",
            "Preview a typed export variant",
            "PlanExportVariantInput",
            RiskClass.READ,
            "app.read",
            "createWorkflowPlan",
            "POST",
            "/api/v1/sessions/{sessionId}/workflow-plans",
            True,
        ),
        ActionSpec(
            "pandrator_execute_workflow_plan",
            "Execute an exact reviewed workflow plan",
            "ExecuteWorkflowPlanInput",
            RiskClass.RUN,
            "app.run",
            "executeWorkflowPlan",
            "POST",
            "/api/v1/workflow-plans/{planId}/execute",
            True,
            True,
            True,
        ),
        ActionSpec(
            "pandrator_cancel_work",
            "Cancel durable work",
            "CancelWorkInput",
            RiskClass.CANCEL,
            "app.cancel",
            "cancelWork",
            "POST",
            "/api/v1/work/{jobId}/cancel",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_download_artifact",
            "Materialize an artifact in the approved local output root",
            "DownloadArtifactInput",
            RiskClass.WRITE,
            "app.read",
            "getArtifactContent",
            "GET",
            "/api/v1/artifacts/{artifactId}/content",
            True,
        ),
        ActionSpec(
            "pandrator_plan_component_change",
            "Preview an exact Manager component plan",
            "PlanComponentChangeInput",
            RiskClass.READ,
            "manager.read",
            "createManagerPlan",
            "POST",
            "/api/v1/manager/plans",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_control_runtime",
            "Control Pandrator or managed service runtime",
            "ControlRuntimeInput",
            RiskClass.MANAGER_RUNTIME,
            "manager.runtime",
            "controlManagerRuntime",
            "POST",
            "/api/v1/manager/runtime/{action}",
            True,
            True,
            True,
        ),
        ActionSpec(
            "pandrator_execute_component_plan",
            "Execute an exact reviewed Manager component plan",
            "ExecuteComponentPlanInput",
            RiskClass.MANAGER_MUTATE,
            "manager.mutate",
            "submitManagerOperation",
            "POST",
            "/api/v1/manager/operations",
            True,
            True,
            True,
        ),
    )
)
