"""Declarative MCP action catalog, independent of handlers and transport."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from .performance_actions import PERFORMANCE_ACTIONS, performance_api_path


class RiskClass(StrEnum):
    READ = "read"
    WRITE = "write"
    RUN = "run"
    CANCEL = "cancel"
    MANAGER_RUNTIME = "manager_runtime"
    MANAGER_MUTATE = "manager_mutate"


@dataclass(frozen=True, slots=True)
class ActionSpec:
    name: str
    title: str
    input_model: str
    risk: RiskClass
    required_scope: str | None
    downstream_operation_id: str | None
    method: str | None
    path: str | None
    enabled: bool
    requires_idempotency: bool = False
    requires_confirmation: bool = False

    @property
    def mutating(self) -> bool:
        return self.risk != RiskClass.READ


class ActionCatalog:
    def __init__(self, actions: tuple[ActionSpec, ...]):
        self._actions = {action.name: action for action in actions}
        if len(self._actions) != len(actions):
            raise ValueError("Action names must be unique.")

    def get(self, name: str) -> ActionSpec:
        return self._actions[name]

    def list(self) -> tuple[ActionSpec, ...]:
        return tuple(self._actions[name] for name in sorted(self._actions))


ACTION_CATALOG = ActionCatalog(
    (
        ActionSpec("pandrator_get_audiobook_setup", "Inspect audiobook setup", "GetAudiobookSetupInput", RiskClass.READ, "app.read", "getAudiobookSetup", "GET", "/api/v1/sessions/{sessionId}/audiobook-setup", True),
        ActionSpec("pandrator_configure_audiobook", "Configure audiobook voice mode", "ConfigureAudiobookInput", RiskClass.WRITE, "app.write", "configureAudiobook", "PATCH", "/api/v1/sessions/{sessionId}/audiobook-setup", True, requires_idempotency=True),
        ActionSpec("pandrator_preview_speech_segment", "Preview a speech-plan segment", "PreviewSpeechSegmentInput", RiskClass.READ, "app.read", "previewSpeechSegment", "POST", "/api/v1/sessions/{sessionId}/speech-plan/preview", True),
        *(ActionSpec(name, title, model, RiskClass(risk), scope, operation, method,
                     performance_api_path(suffix), True, requires_idempotency=risk != "read")
          for _action, name, title, model, risk, scope, operation, method, suffix in PERFORMANCE_ACTIONS),
        ActionSpec(
            "pandrator_explain_system",
            "Explain Pandrator",
            "ExplainSystemInput",
            RiskClass.READ,
            None,
            None,
            None,
            None,
            True,
        ),
        ActionSpec(
            "pandrator_recommend_next_steps",
            "Recommend safe next steps",
            "RecommendNextStepsInput",
            RiskClass.READ,
            "app.read",
            None,
            None,
            None,
            True,
        ),
        ActionSpec(
            "pandrator_get_target_status",
            "Inspect configured target status",
            "TargetStatusInput",
            RiskClass.READ,
            None,
            "getHealth",
            "GET",
            "/api/v1/health",
            True,
        ),
        ActionSpec(
            "pandrator_get_system_status",
            "Inspect Pandrator status",
            "SystemStatusInput",
            RiskClass.READ,
            "app.read",
            "getHealth",
            "GET",
            "/api/v1/health",
            True,
        ),
        ActionSpec(
            "pandrator_get_capabilities",
            "Inspect Pandrator capabilities",
            "CapabilitiesInput",
            RiskClass.READ,
            "app.read",
            "getCapabilities",
            "GET",
            "/api/v1/capabilities",
            True,
        ),
        ActionSpec(
            "pandrator_list_sessions",
            "List Pandrator sessions",
            "ListSessionsInput",
            RiskClass.READ,
            "app.read",
            "listSessions",
            "GET",
            "/api/v1/sessions",
            True,
        ),
        ActionSpec(
            "pandrator_get_session",
            "Inspect a Pandrator session",
            "GetSessionInput",
            RiskClass.READ,
            "app.read",
            "getSession",
            "GET",
            "/api/v1/sessions/{sessionId}",
            True,
        ),
        ActionSpec(
            "pandrator_get_generation_controls",
            "Inspect characters and voice cast",
            "GetGenerationControlsInput",
            RiskClass.READ,
            "app.read",
            "getGenerationControls",
            "GET",
            "/api/v1/sessions/{sessionId}/generation-controls",
            True,
        ),
        ActionSpec(
            "pandrator_update_generation_controls",
            "Update characters and voice cast",
            "UpdateGenerationControlsInput",
            RiskClass.WRITE,
            "app.write",
            "updateGenerationControls",
            "PUT",
            "/api/v1/sessions/{sessionId}/generation-controls",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_get_workflow",
            "Inspect a session workflow",
            "GetWorkflowInput",
            RiskClass.READ,
            "app.read",
            "getWorkflow",
            "GET",
            "/api/v1/sessions/{sessionId}/workflow",
            True,
        ),
        ActionSpec(
            "pandrator_get_media_edit",
            "Inspect media-edit plan state",
            "GetMediaEditArguments",
            RiskClass.READ,
            "app.read",
            "getMediaEdit",
            "GET",
            "/api/v1/sessions/{sessionId}/media-edit",
            True,
        ),
        ActionSpec(
            "pandrator_list_media_edit_cuts",
            "List bounded media-edit cuts",
            "ListMediaEditCutsArguments",
            RiskClass.READ,
            "app.read",
            "listMediaEditCuts",
            "GET",
            "/api/v1/sessions/{sessionId}/media-edit/cuts",
            True,
        ),
        ActionSpec(
            "pandrator_inspect_media_edit_boundary",
            "Inspect a media-edit boundary",
            "InspectMediaEditBoundaryArguments",
            RiskClass.READ,
            "app.read",
            "listMediaEditCuts",
            "GET",
            "/api/v1/sessions/{sessionId}/media-edit/cuts",
            True,
        ),
        ActionSpec(
            "pandrator_plan_media_edit_workflow",
            "Plan a live media-edit workflow procedure",
            "PlanMediaEditWorkflowInput",
            RiskClass.READ,
            "app.read",
            None,
            None,
            None,
            True,
        ),
        ActionSpec(
            "pandrator_prepare_media_edit",
            "Prepare a media-edit plan",
            "PrepareMediaEditArguments",
            RiskClass.WRITE,
            "app.write",
            "prepareMediaEdit",
            "POST",
            "/api/v1/sessions/{sessionId}/media-edit/prepare",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_update_media_edit",
            "Update media-edit keep ranges",
            "UpdateMediaEditArguments",
            RiskClass.WRITE,
            "app.write",
            "updateMediaEdit",
            "PUT",
            "/api/v1/sessions/{sessionId}/media-edit",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_refine_media_edit_boundary",
            "Refine a media-edit boundary",
            "RefineMediaEditBoundaryArguments",
            RiskClass.WRITE,
            "app.write",
            "refineMediaEditBoundary",
            "PATCH",
            "/api/v1/sessions/{sessionId}/media-edit/boundary",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_propose_media_edit",
            "Propose a media edit",
            "ProposeMediaEditArguments",
            RiskClass.RUN,
            "app.run",
            "proposeMediaEdit",
            "POST",
            "/api/v1/sessions/{sessionId}/media-edit/propose",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_render_media_edit",
            "Render a reviewed media edit",
            "RenderMediaEditArguments",
            RiskClass.RUN,
            "app.run",
            "renderMediaEdit",
            "POST",
            "/api/v1/sessions/{sessionId}/media-edit/render",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_preview_subtitles",
            "Preview subtitle cues, transcript segments, and translations",
            "PreviewSubtitlesInput",
            RiskClass.READ,
            "app.read",
            "getSubtitleDocuments",
            "GET",
            "/api/v1/sessions/{sessionId}/subtitles",
            True,
        ),
        ActionSpec(
            "pandrator_replace_subtitle_text",
            "Find and replace text across subtitle cues with revision guard",
            "ReplaceSubtitleTextInput",
            RiskClass.WRITE,
            "app.write",
            "saveSubtitleReview",
            "POST",
            "/api/v1/sessions/{sessionId}/subtitles/{stage}/review",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_patch_subtitle_cues",
            "Patch specific subtitle cues by ordinal with revision guard",
            "PatchSubtitleCuesInput",
            RiskClass.WRITE,
            "app.write",
            "saveSubtitleReview",
            "POST",
            "/api/v1/sessions/{sessionId}/subtitles/{stage}/review",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_import_subtitles",
            "Import reviewed subtitles from raw SRT text or file",
            "ImportSubtitlesInput",
            RiskClass.WRITE,
            "app.write",
            "saveSubtitleReview",
            "POST",
            "/api/v1/sessions/{sessionId}/subtitles/{stage}/review",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_get_session_settings",
            "Inspect effective session settings",
            "GetSessionSettingsInput",
            RiskClass.READ,
            "app.read",
            "getSessionSettings",
            "GET",
            "/api/v1/sessions/{sessionId}/settings/{section}",
            True,
        ),
        ActionSpec(
            "pandrator_describe_parameters",
            "Discover filtered parameter definitions",
            "DescribeParametersInput",
            RiskClass.READ,
            "app.read",
            "getParameterDefinitions",
            "GET",
            "/api/v1/parameter-definitions",
            True,
        ),
        ActionSpec(
            "pandrator_list_sources",
            "List reusable source assets",
            "ListSourcesInput",
            RiskClass.READ,
            "app.read",
            "listSourceAssets",
            "GET",
            "/api/v1/sources",
            True,
        ),
        ActionSpec(
            "pandrator_browse_local_sources",
            "Browse approved local source roots",
            "BrowseLocalSourcesInput",
            RiskClass.READ,
            None,
            None,
            None,
            None,
            True,
        ),
        ActionSpec(
            "pandrator_create_text_source",
            "Create and attach a plain-text source",
            "CreateTextSourceInput",
            RiskClass.WRITE,
            "app.write",
            "initializeChunkUpload",
            "POST",
            "/api/v1/uploads/init",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_import_local_source",
            "Import and attach a local source",
            "ImportLocalSourceInput",
            RiskClass.WRITE,
            "app.write",
            "initializeChunkUpload",
            "POST",
            "/api/v1/uploads/init",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_transcribe",
            "Upload and transcribe a source",
            "TranscribeInput",
            RiskClass.RUN,
            "app.run",
            "createQuickTranscription",
            "POST",
            "/api/v1/transcriptions",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_transcription_get",
            "Inspect transcription status",
            "GetTranscriptionInput",
            RiskClass.READ,
            "app.read",
            "getQuickTranscription",
            "GET",
            "/api/v1/transcriptions/{transcriptionId}",
            True,
        ),
        ActionSpec(
            "pandrator_transcription_result",
            "Read a transcription result page",
            "GetTranscriptionResultInput",
            RiskClass.READ,
            "app.read",
            "getQuickTranscriptionResult",
            "GET",
            "/api/v1/transcriptions/{transcriptionId}/result",
            True,
        ),
        ActionSpec(
            "pandrator_transcription_cancel",
            "Cancel a transcription",
            "CancelTranscriptionInput",
            RiskClass.CANCEL,
            "app.run",
            "cancelQuickTranscription",
            "POST",
            "/api/v1/transcriptions/{transcriptionId}/cancel",
            True,
        ),
        ActionSpec(
            "pandrator_transcription_delete",
            "Delete a transcription",
            "DeleteTranscriptionInput",
            RiskClass.WRITE,
            "app.run",
            "deleteQuickTranscription",
            "DELETE",
            "/api/v1/transcriptions/{transcriptionId}",
            True,
        ),
        ActionSpec(
            "pandrator_list_artifacts",
            "List artifact metadata",
            "ListArtifactsInput",
            RiskClass.READ,
            "app.read",
            "listArtifacts",
            "GET",
            "/api/v1/artifacts",
            True,
        ),
        ActionSpec(
            "pandrator_get_provider_status",
            "Inspect provider readiness",
            "ProviderStatusInput",
            RiskClass.READ,
            "app.read",
            "listProviders",
            "GET",
            "/api/v1/providers",
            True,
        ),
        ActionSpec(
            "pandrator_get_tts_catalog",
            "Inspect TTS services, models, and voices",
            "TtsCatalogInput",
            RiskClass.READ,
            "app.read",
            "listTtsServices",
            "GET",
            "/api/v1/services/tts",
            True,
        ),
        ActionSpec(
            "pandrator_get_audio_cpp_catalogue",
            "Browse the audio.cpp catalogue",
            "AudioCppCatalogueInput",
            RiskClass.READ,
            "app.read",
            "listAudioCppCatalogue",
            "GET",
            "/api/v1/services/audio-cpp/catalogue",
            True,
        ),
        ActionSpec(
            "pandrator_configure_tts",
            "Configure a catalog-backed TTS selection",
            "ConfigureTtsInput",
            RiskClass.WRITE,
            "app.write",
            "putSessionSettings",
            "PUT",
            "/api/v1/sessions/{sessionId}/settings/tts",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_get_voice_catalog",
            "Inspect the voice catalog",
            "VoiceCatalogInput",
            RiskClass.READ,
            "app.read",
            "queryVoiceCatalog",
            "GET",
            "/api/v1/voice-catalog",
            True,
        ),
        ActionSpec(
            "pandrator_update_voice_metadata",
            "Update managed voice details",
            "UpdateVoiceMetadataInput",
            RiskClass.WRITE,
            "app.write",
            "updateVoice",
            "PATCH",
            "/api/v1/voices/{voiceId}",
            True,
        ),
        ActionSpec(
            "pandrator_get_voice_capabilities",
            "Inspect voice design and cloning capabilities",
            "VoiceCatalogCapabilitiesInput",
            RiskClass.READ,
            "app.read",
            "getVoiceCatalogCapabilities",
            "GET",
            "/api/v1/voice-catalog/capabilities",
            True,
        ),
        ActionSpec(
            "pandrator_create_voice",
            "Create a managed voice",
            "VoiceCreateInput",
            RiskClass.WRITE,
            "app.write",
            "createVoice",
            "POST",
            "/api/v1/voices",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_get_voice_samples",
            "Inspect managed voice samples",
            "GetVoiceSamplesInput",
            RiskClass.READ,
            "app.read",
            "listVoiceSamples",
            "GET",
            "/api/v1/voices/{voiceId}/samples",
            True,
        ),
        ActionSpec(
            "pandrator_promote_voice_design",
            "Promote a reviewed voice-design preview",
            "PromoteVoiceDesignInput",
            RiskClass.WRITE,
            "app.write",
            "createVoiceSampleFromPreview",
            "POST",
            "/api/v1/voices/{voiceId}/samples/from-preview",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_import_voice_reference",
            "Import a reviewed managed voice reference",
            "ImportVoiceReferenceInput",
            RiskClass.WRITE,
            "app.write",
            "importVoiceReference",
            "POST",
            "/api/v1/voices/{voiceId}/samples/from-artifact",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_transcribe_voice_sample",
            "Transcribe one managed voice sample",
            "TranscribeVoiceSampleInput",
            RiskClass.WRITE,
            "app.write",
            "transcribeVoiceSample",
            "POST",
            "/api/v1/voices/{voiceId}/samples/{sampleId}/transcribe",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_review_voice_transcript",
            "Review one managed voice transcript",
            "ReviewVoiceTranscriptInput",
            RiskClass.WRITE,
            "app.write",
            "reviewVoiceSampleTranscript",
            "PATCH",
            "/api/v1/voices/{voiceId}/samples/{sampleId}/transcript",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_publish_voice",
            "Publish one managed voice to a provider",
            "PublishVoiceInput",
            RiskClass.WRITE,
            "app.write",
            "publishVoiceToProvider",
            "POST",
            "/api/v1/voices/{voiceId}/providers/{serviceId}",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_audition_voice",
            "Queue one bounded voice audition",
            "AuditionVoiceInput",
            RiskClass.RUN,
            "app.run",
            "previewTtsVoice",
            "POST",
            "/api/v1/services/tts/{serviceId}/preview",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_list_voice_collections",
            "List voice collections",
            "ListVoiceCollectionsInput",
            RiskClass.READ,
            "app.read",
            "listVoiceCollections",
            "GET",
            "/api/v1/voice-collections",
            True,
        ),
        ActionSpec(
            "pandrator_create_voice_collection",
            "Create a voice collection",
            "CreateVoiceCollectionInput",
            RiskClass.WRITE,
            "app.write",
            "createVoiceCollection",
            "POST",
            "/api/v1/voice-collections",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_update_voice_collection",
            "Update a voice collection",
            "UpdateVoiceCollectionInput",
            RiskClass.WRITE,
            "app.write",
            "updateVoiceCollection",
            "PATCH",
            "/api/v1/voice-collections/{collectionId}",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_update_catalog_voice_metadata",
            "Update provider voice catalog metadata",
            "UpdateCatalogVoiceMetadataInput",
            RiskClass.WRITE,
            "app.write",
            "updateCatalogVoiceMetadata",
            "PATCH",
            "/api/v1/voice-catalog/metadata",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_list_work",
            "List durable work",
            "ListWorkInput",
            RiskClass.READ,
            "app.read",
            "listWork",
            "GET",
            "/api/v1/work",
            True,
        ),
        ActionSpec(
            "pandrator_list_generation_runs",
            "List reviewable generation runs",
            "ListGenerationRunsInput",
            RiskClass.READ,
            "app.read",
            "listGenerationRuns",
            "GET",
            "/api/v1/sessions/{sessionId}/generation-runs",
            True,
        ),
        ActionSpec("pandrator_get_speech_plan_status", "Inspect speech-plan review status", "SpeechPlanStatusInput", RiskClass.READ, "app.read", "getSpeechPlanStatus", "GET", "/api/v1/sessions/{sessionId}/generation-plan/status", True),
        ActionSpec("pandrator_prepare_speech_plan", "Prepare a fresh reviewable speech plan", "PrepareSpeechPlanInput", RiskClass.WRITE, "app.write", "prepareSpeechPlan", "POST", "/api/v1/sessions/{sessionId}/generation-plan/prepare", True, True),
        ActionSpec("pandrator_review_speech_plan", "Mark the selected speech plan reviewed", "ReviewSpeechPlanInput", RiskClass.WRITE, "app.write", "reviewSpeechPlan", "POST", "/api/v1/sessions/{sessionId}/generation-plan/review", True, True),
        ActionSpec("pandrator_list_speech_plan_revisions", "List versioned speech plans", "ListSpeechPlanRevisionsInput", RiskClass.READ, "app.read", "listSpeechPlanRevisions", "GET", "/api/v1/sessions/{sessionId}/generation-plan/revisions", True),
        ActionSpec("pandrator_revise_speech_block_plan_batch", "Atomically revise speech-block topology", "ReviseSpeechBlockPlanBatchInput", RiskClass.WRITE, "app.write", "reviseGenerationPlanTopologyBatch", "POST", "/api/v1/sessions/{sessionId}/generation-plan/topology/batch", True, True),
        ActionSpec("pandrator_generate_speech_plan", "Generate a selected speech-plan revision", "GenerateSpeechPlanInput", RiskClass.WRITE, "app.write", "startGenerationRun", "POST", "/api/v1/sessions/{sessionId}/generation-runs", True, True),
        ActionSpec("pandrator_adopt_subtitle_source", "Adopt an existing managed subtitle source", "AdoptSubtitleSourceInput", RiskClass.WRITE, "app.write", "adoptSubtitleSource", "POST", "/api/v1/sessions/{sessionId}/sources/adopt-subtitles", True, True),
        ActionSpec(
            "pandrator_list_generation_segments",
            "List generation segments and audio takes",
            "ListGenerationSegmentsInput",
            RiskClass.READ,
            "app.read",
            "listGenerationSegments",
            "GET",
            "/api/v1/sessions/{sessionId}/generation-segments",
            True,
        ),
        ActionSpec(
            "pandrator_revise_speech_block_plan",
            "Revise generation speech-block topology",
            "ReviseSpeechBlockPlanInput",
            RiskClass.WRITE,
            "app.write",
            "reviseGenerationPlanTopology",
            "POST",
            "/api/v1/sessions/{sessionId}/generation-plan/topology",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_update_generation_segment",
            "Update generation segment text or voice overrides",
            "UpdateGenerationSegmentInput",
            RiskClass.WRITE,
            "app.write",
            "updateGenerationSegment",
            "PATCH",
            "/api/v1/generation-segments/{segmentId}",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_select_take",
            "Select an alternative audio take for a generation segment",
            "SelectTakeInput",
            RiskClass.WRITE,
            "app.write",
            "selectGenerationTake",
            "POST",
            "/api/v1/generation-segments/{segmentId}/takes/{takeId}/select",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_regenerate_segments",
            "Trigger targeted synthesis for specific generation segments",
            "RegenerateSegmentsInput",
            RiskClass.RUN,
            "app.run",
            "startGenerationRun",
            "POST",
            "/api/v1/sessions/{sessionId}/generation-runs",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_assemble_generation_run",
            "Queue output mix assembly for a generation run",
            "AssembleGenerationRunInput",
            RiskClass.RUN,
            "app.run",
            "createOutputAssembly",
            "POST",
            "/api/v1/sessions/{sessionId}/output-assemblies",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_get_work",
            "Inspect durable work",
            "GetWorkInput",
            RiskClass.READ,
            "app.read",
            "getWork",
            "GET",
            "/api/v1/work/{jobId}",
            True,
        ),
        ActionSpec(
            "pandrator_get_work_log",
            "Inspect a redacted work log",
            "GetWorkLogInput",
            RiskClass.READ,
            "app.read",
            "listWorkEvents",
            "GET",
            "/api/v1/work/{jobId}/events",
            True,
        ),
        ActionSpec(
            "pandrator_manager_status",
            "Inspect Pandrator Manager status",
            "SystemStatusInput",
            RiskClass.READ,
            "manager.read",
            "getManagerStatus",
            "GET",
            "/api/v1/manager/status",
            True,
        ),
        ActionSpec(
            "pandrator_manager_doctor",
            "Inspect Pandrator Manager diagnostics",
            "SystemStatusInput",
            RiskClass.READ,
            "manager.read",
            "getManagerDoctorReport",
            "GET",
            "/api/v1/manager/doctor",
            True,
        ),
        ActionSpec(
            "pandrator_list_dispatch_runs",
            "List subtitle dispatch runs",
            "ListDispatchRunsInput",
            RiskClass.READ,
            "app.read",
            "listDispatchRuns",
            "GET",
            "/api/v1/sessions/{sessionId}/dispatch-runs",
            True,
        ),
        ActionSpec(
            "pandrator_get_dispatch_run",
            "Inspect a subtitle dispatch run",
            "GetDispatchRunInput",
            RiskClass.READ,
            "app.read",
            "getDispatchRun",
            "GET",
            "/api/v1/dispatch-runs/{runId}",
            True,
        ),
        ActionSpec(
            "pandrator_get_subtitle_evidence",
            "Inspect subtitle audio evidence",
            "GetSubtitleEvidenceInput",
            RiskClass.READ,
            "app.read",
            "getSubtitleEvidence",
            "GET",
            "/api/v1/subtitle-evidence/{evidenceId}",
            True,
        ),
        ActionSpec(
            "pandrator_request_subtitle_evidence",
            "Escalate a subtitle cue for audio evidence",
            "RequestSubtitleEvidenceInput",
            RiskClass.RUN,
            "app.run",
            "requestSubtitleEvidence",
            "POST",
            "/api/v1/sessions/{sessionId}/subtitle-evidence",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_resolve_subtitle_evidence",
            "Resolve subtitle audio evidence",
            "ResolveSubtitleEvidenceInput",
            RiskClass.RUN,
            "app.run",
            "resolveSubtitleEvidence",
            "POST",
            "/api/v1/sessions/{sessionId}/subtitle-evidence/{evidenceId}/resolve",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_create_dispatch_run",
            "Create a subtitle dispatch run",
            "CreateDispatchRunInput",
            RiskClass.RUN,
            "app.run",
            "createDispatchRun",
            "POST",
            "/api/v1/sessions/{sessionId}/dispatch-runs",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_claim_dispatch_batch",
            "Claim a subtitle dispatch batch",
            "ClaimDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "claimDispatchBatch",
            "POST",
            "/api/v1/dispatch-runs/{runId}/claim",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_renew_dispatch_batch",
            "Renew a subtitle dispatch lease",
            "RenewDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "renewDispatchBatch",
            "POST",
            "/api/v1/dispatch-batches/{batchId}/renew",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_release_dispatch_batch",
            "Release a subtitle dispatch lease",
            "ReleaseDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "releaseDispatchBatch",
            "POST",
            "/api/v1/dispatch-batches/{batchId}/release",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_submit_dispatch_batch",
            "Submit a subtitle dispatch batch",
            "SubmitDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "submitDispatchBatch",
            "POST",
            "/api/v1/dispatch-batches/{batchId}/submit",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_list_source_cleaning_dispatch_runs",
            "List passive PDF/EPUB cleanup runs",
            "ListSourceCleaningDispatchRunsInput",
            RiskClass.READ,
            "app.read",
            "listSourceCleaningDispatchRuns",
            "GET",
            "/api/v1/sessions/{sessionId}/source-cleaning-dispatch-runs",
            True,
        ),
        ActionSpec(
            "pandrator_get_source_cleaning_dispatch_run",
            "Inspect a passive PDF/EPUB cleanup run",
            "GetSourceCleaningDispatchRunInput",
            RiskClass.READ,
            "app.read",
            "getSourceCleaningDispatchRun",
            "GET",
            "/api/v1/source-cleaning-dispatch-runs/{runId}",
            True,
        ),
        ActionSpec(
            "pandrator_create_source_cleaning_dispatch_run",
            "Create a passive PDF/EPUB cleanup run",
            "CreateSourceCleaningDispatchRunInput",
            RiskClass.RUN,
            "app.run",
            "createSourceCleaningDispatchRun",
            "POST",
            "/api/v1/sessions/{sessionId}/source-cleaning-dispatch-runs",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_claim_source_cleaning_dispatch_batch",
            "Claim a PDF/EPUB cleanup phase",
            "ClaimSourceCleaningDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "claimSourceCleaningDispatchBatch",
            "POST",
            "/api/v1/source-cleaning-dispatch-runs/{runId}/claim",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_renew_source_cleaning_dispatch_batch",
            "Renew a PDF/EPUB cleanup lease",
            "RenewSourceCleaningDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "renewSourceCleaningDispatchBatch",
            "POST",
            "/api/v1/source-cleaning-dispatch-batches/{batchId}/renew",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_release_source_cleaning_dispatch_batch",
            "Release a PDF/EPUB cleanup lease",
            "ReleaseSourceCleaningDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "releaseSourceCleaningDispatchBatch",
            "POST",
            "/api/v1/source-cleaning-dispatch-batches/{batchId}/release",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_inspect_source_cleaning_dispatch_extraction",
            "Inspect a leased PDF/EPUB extraction",
            "InspectSourceCleaningDispatchExtractionInput",
            RiskClass.RUN,
            "app.run",
            "inspectSourceCleaningDispatchExtraction",
            "POST",
            "/api/v1/source-cleaning-dispatch-batches/{batchId}/inspect",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_submit_source_cleaning_dispatch_batch",
            "Submit a PDF/EPUB cleanup phase",
            "SubmitSourceCleaningDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "submitSourceCleaningDispatchBatch",
            "POST",
            "/api/v1/source-cleaning-dispatch-batches/{batchId}/submit",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_list_speech_optimization_dispatch_runs",
            "List passive speech-optimization runs",
            "ListSpeechOptimizationDispatchRunsInput",
            RiskClass.READ,
            "app.read",
            "listSpeechOptimizationDispatchRuns",
            "GET",
            "/api/v1/sessions/{sessionId}/speech-optimization-dispatch-runs",
            True,
        ),
        ActionSpec(
            "pandrator_get_speech_optimization_dispatch_run",
            "Inspect a passive speech-optimization run",
            "GetSpeechOptimizationDispatchRunInput",
            RiskClass.READ,
            "app.read",
            "getSpeechOptimizationDispatchRun",
            "GET",
            "/api/v1/speech-optimization-dispatch-runs/{runId}",
            True,
        ),
        ActionSpec(
            "pandrator_create_speech_optimization_dispatch_run",
            "Create a passive speech-optimization run",
            "CreateSpeechOptimizationDispatchRunInput",
            RiskClass.RUN,
            "app.run",
            "createSpeechOptimizationDispatchRun",
            "POST",
            "/api/v1/sessions/{sessionId}/speech-optimization-dispatch-runs",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_claim_speech_optimization_dispatch_batch",
            "Claim a passive speech-text batch",
            "ClaimSpeechOptimizationDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "claimSpeechOptimizationDispatchBatch",
            "POST",
            "/api/v1/speech-optimization-dispatch-runs/{runId}/claim",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_renew_speech_optimization_dispatch_batch",
            "Renew a speech-optimization lease",
            "RenewSpeechOptimizationDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "renewSpeechOptimizationDispatchBatch",
            "POST",
            "/api/v1/speech-optimization-dispatch-batches/{batchId}/renew",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_release_speech_optimization_dispatch_batch",
            "Release a speech-optimization lease",
            "ReleaseSpeechOptimizationDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "releaseSpeechOptimizationDispatchBatch",
            "POST",
            "/api/v1/speech-optimization-dispatch-batches/{batchId}/release",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_submit_speech_optimization_dispatch_batch",
            "Submit a passive speech-text batch",
            "SubmitSpeechOptimizationDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "submitSpeechOptimizationDispatchBatch",
            "POST",
            "/api/v1/speech-optimization-dispatch-batches/{batchId}/submit",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_list_media_edit_dispatch_runs",
            "List passive media-edit runs",
            "ListMediaEditDispatchRunsInput",
            RiskClass.READ,
            "app.read",
            "listMediaEditDispatchRuns",
            "GET",
            "/api/v1/sessions/{sessionId}/media-edit-dispatch-runs",
            True,
        ),
        ActionSpec(
            "pandrator_get_media_edit_dispatch_run",
            "Inspect a passive media-edit run",
            "GetMediaEditDispatchRunInput",
            RiskClass.READ,
            "app.read",
            "getMediaEditDispatchRun",
            "GET",
            "/api/v1/media-edit-dispatch-runs/{runId}",
            True,
        ),
        ActionSpec(
            "pandrator_create_media_edit_dispatch_run",
            "Create a passive media-edit run",
            "CreateMediaEditDispatchRunInput",
            RiskClass.RUN,
            "app.run",
            "createMediaEditDispatchRun",
            "POST",
            "/api/v1/sessions/{sessionId}/media-edit-dispatch-runs",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_claim_media_edit_dispatch_batch",
            "Claim a passive media-edit batch",
            "ClaimMediaEditDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "claimMediaEditDispatchBatch",
            "POST",
            "/api/v1/media-edit-dispatch-runs/{runId}/claim",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_renew_media_edit_dispatch_batch",
            "Renew a media-edit lease",
            "RenewMediaEditDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "renewMediaEditDispatchBatch",
            "POST",
            "/api/v1/media-edit-dispatch-batches/{batchId}/renew",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_release_media_edit_dispatch_batch",
            "Release a media-edit lease",
            "ReleaseMediaEditDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "releaseMediaEditDispatchBatch",
            "POST",
            "/api/v1/media-edit-dispatch-batches/{batchId}/release",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_submit_media_edit_dispatch_batch",
            "Submit a passive media-edit batch",
            "SubmitMediaEditDispatchBatchInput",
            RiskClass.RUN,
            "app.run",
            "submitMediaEditDispatchBatch",
            "POST",
            "/api/v1/media-edit-dispatch-batches/{batchId}/submit",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_create_session",
            "Create a Pandrator session",
            "CreateSessionInput",
            RiskClass.WRITE,
            "app.write",
            "createSession",
            "POST",
            "/api/v1/sessions",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_update_session",
            "Update a Pandrator session",
            "UpdateSessionInput",
            RiskClass.WRITE,
            "app.write",
            "updateSession",
            "PATCH",
            "/api/v1/sessions/{sessionId}",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_trash_session",
            "Move a session to recoverable trash",
            "TrashSessionInput",
            RiskClass.WRITE,
            "app.write",
            "trashSession",
            "DELETE",
            "/api/v1/sessions/{sessionId}",
            True,
        ),
        ActionSpec(
            "pandrator_restore_session",
            "Restore a session from recoverable trash",
            "RestoreSessionInput",
            RiskClass.WRITE,
            "app.write",
            "restoreSession",
            "POST",
            "/api/v1/sessions/{sessionId}/restore",
            True,
        ),
        ActionSpec(
            "pandrator_attach_existing_source",
            "Attach a reusable source asset",
            "AttachExistingSourceInput",
            RiskClass.WRITE,
            "app.write",
            "attachSessionSource",
            "POST",
            "/api/v1/sessions/{sessionId}/sources",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_update_session_settings",
            "Replace full session settings section; omitted fields removed",
            "UpdateSessionSettingsInput",
            RiskClass.WRITE,
            "app.write",
            "putSessionSettings",
            "PUT",
            "/api/v1/sessions/{sessionId}/settings/{section}",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_patch_session_settings",
            "Patch one session settings section",
            "PatchSessionSettingsInput",
            RiskClass.WRITE,
            "app.write",
            "patchSessionSettings",
            "PATCH",
            "/api/v1/sessions/{sessionId}/settings/{section}",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_delete_output",
            "Permanently delete one session output file",
            "DeleteOutputInput",
            RiskClass.WRITE,
            "app.write",
            "deleteOutputArtifact",
            "DELETE",
            "/api/v1/sessions/{sessionId}/outputs/{artifactId}",
            True,
        ),
        ActionSpec(
            "pandrator_plan_workflow",
            "Preview an exact workflow execution plan",
            "PlanWorkflowInput",
            RiskClass.READ,
            "app.read",
            "createWorkflowPlan",
            "POST",
            "/api/v1/sessions/{sessionId}/workflow-plans",
            True,
        ),
        ActionSpec(
            "pandrator_plan_orchestrated_workflow",
            "Plan model-operated passive stages and deferred native execution",
            "PlanOrchestratedWorkflowInput",
            RiskClass.READ,
            "app.read",
            None,
            None,
            None,
            True,
        ),
        ActionSpec(
            "pandrator_plan_export_variant",
            "Preview a typed export variant",
            "PlanExportVariantInput",
            RiskClass.READ,
            "app.read",
            "createWorkflowPlan",
            "POST",
            "/api/v1/sessions/{sessionId}/workflow-plans",
            True,
        ),
        ActionSpec(
            "pandrator_execute_workflow_plan",
            "Execute an exact reviewed workflow plan",
            "ExecuteWorkflowPlanInput",
            RiskClass.RUN,
            "app.run",
            "executeWorkflowPlan",
            "POST",
            "/api/v1/workflow-plans/{planId}/execute",
            True,
            True,
            True,
        ),
        ActionSpec(
            "pandrator_cancel_work",
            "Cancel durable work",
            "CancelWorkInput",
            RiskClass.CANCEL,
            "app.cancel",
            "cancelWork",
            "POST",
            "/api/v1/work/{jobId}/cancel",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_download_artifact",
            "Materialize an artifact in the approved local output root",
            "DownloadArtifactInput",
            RiskClass.WRITE,
            "app.read",
            "getArtifactContent",
            "GET",
            "/api/v1/artifacts/{artifactId}/content",
            True,
        ),
        ActionSpec(
            "pandrator_plan_component_change",
            "Preview an exact Manager component plan",
            "PlanComponentChangeInput",
            RiskClass.READ,
            "manager.read",
            "createManagerPlan",
            "POST",
            "/api/v1/manager/plans",
            True,
            True,
        ),
        ActionSpec(
            "pandrator_control_runtime",
            "Control Pandrator or managed service runtime",
            "ControlRuntimeInput",
            RiskClass.MANAGER_RUNTIME,
            "manager.runtime",
            "controlManagerRuntime",
            "POST",
            "/api/v1/manager/runtime/{action}",
            True,
            True,
            True,
        ),
        ActionSpec(
            "pandrator_execute_component_plan",
            "Execute an exact reviewed Manager component plan",
            "ExecuteComponentPlanInput",
            RiskClass.MANAGER_MUTATE,
            "manager.mutate",
            "submitManagerOperation",
            "POST",
            "/api/v1/manager/operations",
            True,
            True,
            True,
        ),
    )
)
