"""Shared declarative metadata for the portable performance MCP actions."""

_BASE = "/api/v1/sessions/{sessionId}/performance-plans"
# action, tool name, title, input model, risk/scope, operation, method, suffix
PERFORMANCE_ACTIONS = (
    (
        "list",
        "pandrator_list_performance_plans",
        "List speech direction plans",
        "ListPerformancePlansInput",
        "read",
        "app.read",
        "listPerformancePlans",
        "GET",
        "",
    ),
    (
        "get",
        "pandrator_get_performance_plan",
        "Inspect speech directions",
        "GetPerformancePlanInput",
        "read",
        "app.read",
        "getPerformancePlan",
        "GET",
        "/{planId}",
    ),
    (
        "create",
        "pandrator_create_performance_plan",
        "Create a speech direction draft",
        "CreatePerformancePlanInput",
        "run",
        "app.run",
        "createPerformancePlan",
        "POST",
        "",
    ),
    (
        "edit",
        "pandrator_edit_performance_plan",
        "Edit or lock speech directions",
        "EditPerformancePlanInput",
        "write",
        "app.write",
        "editPerformancePlan",
        "PATCH",
        "/{planId}",
    ),
    (
        "adopt",
        "pandrator_adopt_performance_plan",
        "Adopt reviewed speech directions",
        "AdoptPerformancePlanInput",
        "write",
        "app.write",
        "adoptPerformancePlan",
        "POST",
        "/{planId}/adopt",
    ),
    (
        "preview",
        "pandrator_preview_performance_plan",
        "Preview a compiled request without audio",
        "PreviewPerformancePlanInput",
        "read",
        "app.read",
        "previewPerformancePlan",
        "POST",
        "/{planId}/preview",
    ),
    (
        "analyse",
        "pandrator_analyse_performance_plan",
        "Resume delivery analysis with the configured LLM",
        "AnalysePerformancePlanInput",
        "run",
        "app.run",
        "analysePerformancePlan",
        "POST",
        "/{planId}/analyse",
    ),
    (
        "claim",
        "pandrator_claim_performance_batch",
        "Claim a speech direction batch",
        "ClaimPerformanceBatchInput",
        "run",
        "app.run",
        "claimPerformanceBatch",
        "POST",
        "/{planId}/claim",
    ),
    (
        "submit",
        "pandrator_submit_performance_batch",
        "Submit validated speech directions",
        "SubmitPerformanceBatchInput",
        "run",
        "app.run",
        "submitPerformanceBatch",
        "POST",
        "/{planId}/batches/{batchId}/submit",
    ),
    (
        "renew",
        "pandrator_renew_performance_batch",
        "Renew a speech direction batch lease",
        "RenewPerformanceBatchInput",
        "run",
        "app.run",
        "renewPerformanceBatch",
        "POST",
        "/{planId}/batches/{batchId}/renew",
    ),
    (
        "release",
        "pandrator_release_performance_batch",
        "Release a speech direction batch lease",
        "ReleasePerformanceBatchInput",
        "run",
        "app.run",
        "releasePerformanceBatch",
        "POST",
        "/{planId}/batches/{batchId}/release",
    ),
)


def performance_api_path(suffix: str) -> str:
    return _BASE + suffix
